#### Working with LinkedIN URLs of Key People

In [16]:
import os
import time
import logging
import traceback
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from urllib.parse import urlparse, urlunparse
from rapidfuzz import fuzz
import re

Metadata=pd.read_excel(r"C:\Users\IlaBarshilia\OneDrive - OIA Global\VS_Code\Hoosier_WebScraping_Output-Metadata_All_Pages.xlsx")
print(Metadata.shape)
Metadata = Metadata.loc[(Metadata["Consider for Detailed Scraping"] == "Y") & (Metadata["Is in Indiana State?"] == "Yes"), ["Employer Name", "City"]].drop_duplicates()
Metadata['Employer Name'] = Metadata['Employer Name'].str.replace(r"[#']", '', regex=True)
Metadata_scraped_index = Metadata[Metadata['Employer Name']=="Kendall Pool Svc"].index[0]
Metadata = Metadata.loc[Metadata_scraped_index+1:]
print(Metadata.shape)

def clean_company_name(name):
    name = name.lower()
    name = re.sub(r'\b(company|co|ltd|limited|inc|corp|corporation|pvt|private|llc|llp|plc|gmbh|s\.a\.|s\.r\.l\.|bv|ag)\b', '', name)
    name = re.sub(r'[^\w\s]', '', name)  
    name = re.sub(r'\s+', ' ', name).strip()
    return name

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\IlaBarshilia\\OneDrive - OIA Global\\VS_Code\\Hoosier_WebScraping_Output-Metadata_All_Pages.xlsx'

In [11]:
Metadata.head()

             Employer Name          City
110041  Jehovahs Witnesses   Charlestown
110050  Jehovahs Witnesses  Indianapolis
110061  Jehovahs Witnesses        Aurora
110067  Jehovahs Witnesses   Bloomington
110068  Jehovahs Witnesses      Bluffton

In [12]:
# Setup logging
logging.basicConfig(
    level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S',
    force=True)  # Force logging to overwrite any previous settings

# Load credentials from environment variables (recommended)
EMAIL = "bmorris@lacydiversified.com"
PASSWORD = "Oiaglobal25!"

# Setup Chrome options
options = Options()
# options.add_argument("--headless")  # Uncomment if running in headless mode
driver = webdriver.Chrome(options=options)
wait = WebDriverWait(driver, 20)

# Step 1: Open Capital IQ login page
driver.get("https://www.capitaliq.spglobal.com")
logging.info("Opened Capital IQ login page.")

# Step 2: Enter email
email_input = wait.until(EC.presence_of_element_located((By.ID, "input28")))
email_input.clear()
email_input.send_keys(EMAIL)
logging.info("Email entered.")

# Step 3: Click "Next"
next_button = wait.until(EC.element_to_be_clickable((By.XPATH, '//input[@type="submit" and @value="Next"]')))
next_button.click()
logging.info("Email submitted.")

# Step 4: Enter password
password_input = wait.until(EC.presence_of_element_located((By.XPATH, '//input[@placeholder="Password"]')))
password_input.send_keys(PASSWORD)

# Step 5: Click "Sign In"
sign_in_button = wait.until(EC.element_to_be_clickable((By.XPATH, '//input[@type="submit" and @value="Sign In"]')))
sign_in_button.click()
logging.info("Password submitted.")

# Step 6: Wait for login to complete
wait.until(EC.presence_of_element_located((By.XPATH, '//div[contains(@class, "header")]')))
logging.info("Login successful and page loaded.")

# Step 7: Accept cookie popup if present
try:
    cookie_button = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, '//button[contains(text(), "Accept") or contains(text(), "Agree")]')))
    cookie_button.click()
except:
    pass

# Step 8: Navigate directly to the search results URL
all_company_data = []

for index, row in Metadata.iterrows():
    search_term = row['Employer Name']
    search_city = row['City']
    
    search_url = f"https://www.capitaliq.spglobal.com/apisv3/spg-webplatform-core/search/searchResults?vertical=private_companies_mi-gss&q={search_term.replace(' ', '%20')}"
    driver.get(search_url)
    logging.info(f"Processing: '{search_term}' Company in '{search_city}' City")
    try:
        clear_all_button = WebDriverWait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, "//button[@aria-label='Clear All']")))
        clear_all_button.click()
    except:
        pass

    dropdown_toggle = wait.until(EC.element_to_be_clickable((By.XPATH, "//button[@title='Select Geography']")))
    dropdown_toggle.click()
    search_input = wait.until(EC.presence_of_element_located((By.XPATH, "//input[@placeholder='Search Geography']")))
    search_input.send_keys("Indiana")
    # Wait for the "USA" option to appear and click it
    usa_option = wait.until(EC.element_to_be_clickable((By.XPATH, "//div[@title='Indiana' and contains(@class, 'css-b0wbzt')]")))
    usa_option.click()

    # Step 8: Check if search results loaded
    search_results_found = True
    try:
        wait.until(EC.presence_of_element_located((By.CLASS_NAME, "css-7mog2u")))
    except:
        search_results_found = False
        logging.warning(f"No Search results for {search_term}, continuing to next company")
        company_data = {
            "Employer Name": search_term,
            "City": search_city,
            "NAICS Code": None,
            "Industry": None,
            "Description": None,
            "Website URL": None,
            "Headquarters": None,
            "Current_Headcount": None,
            "Percent_Change_in_HC": None,
            "Change_in_HC": None,
            "CEO Name": None,
            "CEO Profile Link": None,
            "LinkedIN URL": None,
            "Key People": None
        }
        all_company_data.append(company_data)
        
    if not search_results_found:
        continue

    # Step 8.1: Handle cookie popup
    try:
        cookie_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//button[contains(text(), "Accept") or contains(text(), "Agree")]')))
        cookie_button.click()
    except:
        pass

    # Step 9: Change results per page to 50
    try:
        show_label = wait.until(EC.presence_of_element_located((By.CLASS_NAME, "css-7mog2u")))
        driver.execute_script("arguments[0].scrollIntoView(true);", show_label)
        time.sleep(1)

        dropdown_trigger = wait.until(EC.element_to_be_clickable((By.XPATH, '//button[@type="button" and @title="20"]')))
        driver.execute_script("arguments[0].click();", dropdown_trigger)
        time.sleep(1)

        options = wait.until(EC.presence_of_all_elements_located((By.XPATH, '//div[@title="50" and contains(@class, "css-11d71qm")]')))
        for option in options:
            if option.is_displayed():
                driver.execute_script("arguments[0].click();", option)
                # logging.info("✅ Changed results per page to 50")
                time.sleep(3)
                break
    except Exception as e:
        pass

    # Step 10: Find matching company by city
    try:
        WebDriverWait(driver, 10).until(EC.presence_of_all_elements_located((By.XPATH, '//a[contains(@href, "/web/client#company/profile?id=")]')))
        company_links = driver.find_elements(By.XPATH, '//a[contains(@href, "/web/client#company/profile?id=")]')
        match_found = False
        
        for link in company_links:
            try:
                found_city_text = link.find_element(By.XPATH, './ancestor::div[3]').text
                found_company_text = link.text.strip()
                cleaned_found_company = clean_company_name(found_company_text)
                if search_city.lower() in found_city_text.lower():
                    cleaned_search_company = clean_company_name(search_term)
                    similarity = fuzz.token_sort_ratio(cleaned_search_company, cleaned_found_company)
                    if similarity > 80:  # Adjust threshold as needed
                        logging.info(f"✅ Match found for: {link.text.strip()} | City: {search_city} | Similarity Score: {similarity}")
                        driver.execute_script("arguments[0].click();", link)
                        match_found = True

                        # Step 11: Initialize company_data for matched company
                        company_data = {
                            "Employer Name": search_term,
                            "City": search_city,
                            "NAICS Code": None,
                            "Industry": None,
                            "Description": None,
                            "Website URL": None,
                            "Headquarters": None,
                            "Current_Headcount": None,
                            "Percent_Change_in_HC": None,
                            "Change_in_HC": None,
                            "CEO Name": None,
                            "CEO Profile Link": None,
                            "LinkedIN URL": None,
                            "Key People": None
                        }
                        # Continue with data extraction steps...

                        # 1. NAICS Code
                        try:
                            naics_element = wait.until(EC.presence_of_element_located(
                                (By.XPATH, '//div[@id="naics"]//span[@id="naicsLessTextSpan"]/b')))
                            company_data["NAICS Code"] = naics_element.text.strip()
                        except Exception as e:
                            pass

                        # 2. Industry
                        try:
                            industry_element = wait.until(EC.presence_of_element_located(
                                (By.CSS_SELECTOR, 'h6[data-testid="company-industry-mini-body"]')))
                            company_data["Industry"] = industry_element.text.strip()
                        except Exception as e:
                            pass

                        # 3. Description
                        try:
                            # Try clicking "VIEW ALL" if it exists
                            try:
                                view_all_button = wait.until(EC.element_to_be_clickable((By.XPATH, '//a[contains(text(), "VIEW ALL")]')))
                                view_all_button.click()
                                time.sleep(1)
                            except:
                                pass

                            # Now extract the description
                            description_element = wait.until(EC.presence_of_element_located((By.ID, "compDesc")))
                            description = description_element.text.strip()

                            # Clean up if "VIEW LESS" is included
                            if "VIEW LESS" in description:
                                description = description.split("VIEW LESS")[0].strip()
                            
                            # Remove "As of Date" line if present
                            if "As of Date:" in description:
                                description = description.split("As of Date:")[0].strip()

                            company_data["Description"] = description

                        except Exception as e:
                            company_data["Description"] = None

                        # try:
                        #     view_all_button = wait.until(EC.element_to_be_clickable(
                        #         (By.XPATH, '//a[contains(text(), "VIEW ALL")]')))
                        #     view_all_button.click()
                        #     time.sleep(1)
                        #     description_element = wait.until(EC.presence_of_element_located((By.ID, "compDesc")))
                        #     description = description_element.text.strip()
                        #     if "VIEW LESS" in description:
                        #         description = description.split("VIEW LESS")[0].strip()
                        #     company_data["Description"] = description
                        # except Exception as e:
                        #     print("Description not found!")

                        # 4. Website URL
                        try:
                            cpweblink_element = wait.until(EC.presence_of_element_located((By.CLASS_NAME, "cpweblink")))
                            company_data["Website URL"] = cpweblink_element.find_element(By.TAG_NAME, "a").get_attribute("href")
                        except Exception as e:
                            pass

                        # 5. Headquarters
                        try:
                            block_label_element = wait.until(EC.presence_of_element_located((By.CLASS_NAME, "blockLabel")))
                            hq_element = block_label_element.find_element(By.XPATH, "following-sibling::*[1]")
                            lines = hq_element.text.splitlines()
                            company_data["Headquarters"] = ', '.join([line.strip() for line in lines if line.strip()])
                        except Exception as e:
                            pass

                        # 6. Current Headcount
                        try:
                            headcount_element = wait.until(EC.presence_of_element_located((
                                By.XPATH, '//div[@class="spg-d-flex"]/h6[@class="spg-heading spg-heading--xxsmall spg-text-nowrap"]')))
                            company_data["Current_Headcount"] = headcount_element.text.strip()
                        except Exception as e:
                            pass

                        # 7. Percent Change in Headcount
                        try:
                            percent_change = wait.until(EC.presence_of_element_located((By.XPATH, '//strong[@class="spg-ml-xs"]')))
                            company_data["Percent_Change_in_HC"] = percent_change.text.strip().replace('%', '')
                        except Exception as e:
                            pass

                        # 8. Change in Headcount Direction
                        try:
                            change_type = wait.until(EC.presence_of_element_located((By.XPATH,
                                '//div[contains(@class, "spg-d-flex") and contains(@class, "spg-align-center")]//span[@data-icon]')))
                            icon_html = change_type.get_attribute('outerHTML')
                            if 'caret-up' in icon_html:
                                company_data["Change_in_HC"] = 1
                            elif 'caret-down' in icon_html:
                                company_data["Change_in_HC"] = -1
                            else:
                                company_data["Change_in_HC"] = 0
                        except Exception as e:
                            pass

                        # 9. CEO Name and Profile Link
                        try:
                            ceo_element = wait.until(EC.presence_of_element_located((
                                By.CSS_SELECTOR, 'a[data-testid="ribbon-ceo"].spg-text-medium.css-12tcig2.css-1b9i013')))
                            company_data["CEO Name"] = ceo_element.text
                            company_data["CEO Profile Link"] = ceo_element.get_attribute("href")
                        except Exception as e:
                            pass

                        # 11. Officers
                        try:
                            # Step 1: Click the "More" link under Officers & Directors
                            more_button = wait.until(EC.element_to_be_clickable((By.XPATH, '//div[@id="offDirectors"]//a[contains(text(), "More")]')))
                            driver.execute_script("arguments[0].click();", more_button)
                            time.sleep(5)

                            # Step 2: Wait for the table to appear
                            wait.until(EC.presence_of_element_located((By.XPATH, "//div[contains(@class, 'ag-root-wrapper')]")))
                            # Locate the grid rows
                            rows = driver.find_elements(By.XPATH, "//div[contains(@class, 'ag-center-cols-container')]/div[contains(@class, 'ag-row')]")

                            merged_data = []
                            for i, row in enumerate(rows):
                                try:
                                    # Each cell is a div with class ag-cell
                                    cells = row.find_elements(By.XPATH, ".//div[contains(@class, 'ag-cell')]")
                                    if len(cells) >= 2:
                                        name = cells[0].text.strip()
                                        title = cells[1].text.strip()
                                        merged_data.append({
                                            "Name": name if name else "[No Name]",
                                            "Title": title if title else "[No Title]"
                                        })

                                except Exception as e:
                                    pass

                            # final_output = '; '.join(merged_data)
                            company_data["Key People"] = merged_data
                            # Navigate to the company's LinkedIn "people" page
                        except Exception as e:
                            company_data["Key People"] = None

                        
                        if company_data.get("Key People") is not None:
                            # Step 12: Get LinkedIN URLs of Key People
                            try:
                                wait = WebDriverWait(driver, 10)
                                # Find the span with the text and get its parent anchor tag
                                linkedin_element = driver.find_element(By.CSS_SELECTOR, 'a.spg-link[aria-label="View LinkedIn Professional"]')
                                linkedin_url = linkedin_element.get_attribute('href')
                                parsed_url = urlparse(linkedin_url)
                                clean_path = parsed_url.path.replace('//', '/').rstrip('/')
                                clean_url = urlunparse(parsed_url._replace(path=clean_path, query=''))
                                company_data["LinkedIN URL"] = clean_url
                                driver.execute_script("window.open(arguments[0]);", clean_url)
                                driver.switch_to.window(driver.window_handles[-1])
                            except Exception as e:
                                company_data["LinkedIN URL"] = None  
                                
                            # After switching to the LinkedIn tab
                            # Step 13: Log in to LinkedIn
                            try:
                                # Wait for login page to load
                                wait.until(EC.presence_of_element_located((By.ID, 'username')))

                                # Enter credentials
                                username_input = driver.find_element(By.ID, 'username')
                                password_input = driver.find_element(By.ID, 'password')

                                username_input.send_keys("ilabarshilia@gmail.com")  # Replace with your LinkedIn email
                                password_input.send_keys("Iambrilliant20")           # Replace with your LinkedIn password

                                # Click login
                                login_button = driver.find_element(By.XPATH, '//button[@type="submit"]')
                                login_button.click()

                                # Wait for login to complete
                                wait.until(EC.presence_of_element_located((By.ID, 'global-nav-search')))
                            except Exception as e:
                                print("Login failed")

                            # Step 2: Search each person and extract profile URL
                            linkedin_profiles = []
                            for person in company_data["Key People"]:
                                name = person.get("Name")
                                try:
                                    # Locate and use the LinkedIn search bar
                                    driver.get(linkedin_url)
                                    search_box = wait.until(EC.presence_of_element_located((By.ID, 'people-search-keywords')))
                                    search_box.clear()
                                    search_box.send_keys(name)
                                    search_box.send_keys(Keys.RETURN)
                                    time.sleep(5)

                                    # Wait for and extract the first profile link
                                    profile_link = wait.until(EC.presence_of_element_located((By.XPATH, '//a[contains(@href, "/in/")]')))
                                    person["LinkedIN Profile"] = profile_link.get_attribute('href')
                                except Exception as e:
                                    linkedin_profiles[name] = None
                                
                        all_company_data.append(company_data)
                        break
            except Exception as e:
                company_data = {
                "Employer Name": search_term,
                "City": search_city,
                "NAICS Code": None,
                "Industry": None,
                "Description": None,
                "Website URL": None,
                "Headquarters": None,
                "Current_Headcount": None,
                "Percent_Change_in_HC": None,
                "Change_in_HC": None,
                "CEO Name": None,
                "CEO Profile Link": None,
                "LinkedIN URL": None,
                "Key People": None
            }
                all_company_data.append(company_data)
                print(f"⚠️ Error processing link")


        if not match_found:
            logging.info(f"❗No matching company found for search_term: {search_term} with search_city:{search_city}")
            company_data = {
                "Employer Name": search_term,
                "City": search_city,
                "NAICS Code": None,
                "Industry": None,
                "Description": None,
                "Website URL": None,
                "Headquarters": None,
                "Current_Headcount": None,
                "Percent_Change_in_HC": None,
                "Change_in_HC": None,
                "CEO Name": None,
                "CEO Profile Link": None,
                "LinkedIN URL": None,
                "Key People": None
            }
            all_company_data.append(company_data)
            continue

    except Exception as e:
        print(f"❌ Error locating company links")
        company_data = {
                "Employer Name": search_term,
                "City": search_city,
                "NAICS Code": None,
                "Industry": None,
                "Description": None,
                "Website URL": None,
                "Headquarters": None,
                "Current_Headcount": None,
                "Percent_Change_in_HC": None,
                "Change_in_HC": None,
                "CEO Name": None,
                "CEO Profile Link": None,
                "LinkedIN URL": None,
                "Key People": None
            }
        all_company_data.append(company_data)
        continue

driver.quit()

2025-08-13 13:53:49 - INFO - Opened Capital IQ login page.
2025-08-13 13:53:57 - INFO - Email entered.
2025-08-13 13:53:57 - INFO - Email submitted.
2025-08-13 13:54:00 - INFO - Password submitted.
2025-08-13 13:54:00 - INFO - Login successful and page loaded.
2025-08-13 13:54:21 - INFO - Processing: 'Jehovahs Witnesses' Company in 'Charlestown' City

❌ Error locating company links

2025-08-13 13:55:09 - INFO - Processing: 'Jehovahs Witnesses' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 13:55:53 - INFO - Processing: 'Jehovahs Witnesses' Company in 'Aurora' City

❌ Error locating company links

2025-08-13 13:56:36 - INFO - Processing: 'Jehovahs Witnesses' Company in 'Bloomington' City

❌ Error locating company links

2025-08-13 13:57:20 - INFO - Processing: 'Jehovahs Witnesses' Company in 'Bluffton' City

❌ Error locating company links

2025-08-13 13:58:04 - INFO - Processing: 'Jehovahs Witnesses Christian' Company in 'Indianapolis' City
2025-08-13 13:58:25 - WARNING - No Search results for Jehovahs Witnesses Christian, continuing to next company
2025-08-13 13:58:26 - INFO - Processing: 'Jehovahs Witnesses Craigwood' Company in 'Indianapolis' City
2025-08-13 13:58:48 - WARNING - No Search results for Jehovahs Witnesses Craigwood, continuing to next company
2025-08-13 13:58:48 - INFO - Processing: 'Jehovahs Witnesses Devon Hls' Company in 'Indianapolis' City
2025-08-13 13:59:10 - WARNING - No Search results for Jehovahs Witnesses Devon Hls, continuing to next company
2025-08-13 13:59:11 - INFO - Processing: 'Jehovahs Witnesses North' Company in 'Anderson' City
2025-08-13 13:59:32 - WARNING - No Search results for Jehovahs Witnesses North, continuing to next company
2025-08-13 13:59:33 - INFO - Processing: 'Jemison Laundry Svc Co' Company in 'Indianapolis' City
2025-08-13 13:59:55 - WARNING - No Search results for Jemison Laundry Svc Co, continuing to next company
2025-08-13 13:59:56 - INFO - Processing: 'Jenkins Career Corner' Company in 'Indianapolis' City
2025-08-13 14:00:18 - WARNING - No Search results for Jenkins Career Corner, continuing to next company
2025-08-13 14:00:18 - INFO - Processing: 'Jenkins Motor Shop' Company in 'Bedford' City
2025-08-13 14:00:40 - WARNING - No Search results for Jenkins Motor Shop, continuing to next company
2025-08-13 14:00:40 - INFO - Processing: 'Jennifer Cattet & Assoc Llc' Company in 'Indianapolis' City
2025-08-13 14:01:02 - WARNING - No Search results for Jennifer Cattet & Assoc Llc, continuing to next company
2025-08-13 14:01:03 - INFO - Processing: 'Jennifer Dykstra Inc' Company in 'Indianapolis' City
2025-08-13 14:01:26 - WARNING - No Search results for Jennifer Dykstra Inc, continuing to next company
2025-08-13 14:01:27 - INFO - Processing: 'Jennings County Pallet Inc' Company in 'Butlerville' City
2025-08-13 14:01:46 - INFO - ✅ Match found for: Jennings County Pallets, Inc. | City: Butlerville | Similarity Score: 97.77777777777777
2025-08-13 14:04:36 - INFO - Processing: 'Jennings Trucking Llc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:05:21 - INFO - Processing: 'Jenny Nails' Company in 'Bloomington' City

❌ Error locating company links

2025-08-13 14:06:05 - INFO - Processing: 'Jenny Uni2 Salon De Belleza' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:06:50 - INFO - Processing: 'Jenson Industries' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:07:33 - INFO - Processing: 'Jent Construction' Company in 'Aurora' City

❌ Error locating company links

2025-08-13 14:08:17 - INFO - Processing: 'Jent Family Construction' Company in 'Aurora' City
2025-08-13 14:08:40 - WARNING - No Search results for Jent Family Construction, continuing to next company
2025-08-13 14:08:40 - INFO - Processing: 'Jent Property Management' Company in 'Aurora' City
2025-08-13 14:09:04 - INFO - ❗No matching company found for search_term: Jent Property Management with search_city:Aurora
2025-08-13 14:09:09 - INFO - Processing: 'Jerden Industries Inc' Company in 'Bloomington' City
2025-08-13 14:09:28 - INFO - ✅ Match found for: Jerden Industries Inc. | City: Bloomington | Similarity Score: 100.0
2025-08-13 14:12:02 - INFO - Processing: 'Jericho Advanced Training' Company in 'Bluffton' City

❌ Error locating company links

2025-08-13 14:12:48 - INFO - Processing: 'Jerico Metal Specialties Inc' Company in 'Bloomington' City
2025-08-13 14:13:07 - INFO - ✅ Match found for: Jerico Metal Specialties, LLC | City: Bloomington | Similarity Score: 100.0

Login failed
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link

2025-08-13 14:15:49 - INFO - Processing: 'Jerry Aigner Construction Inc' Company in 'Boonville' City
2025-08-13 14:16:08 - INFO - ✅ Match found for: Aigner Construction Inc. | City: Boonville | Similarity Score: 86.36363636363636

Login failed
⚠️ Error processing link
⚠️ Error processing link

2025-08-13 14:17:13 - INFO - Processing: 'Jerry Burton Masonry' Company in 'Bloomington' City

❌ Error locating company links

2025-08-13 14:17:47 - INFO - Processing: 'Jerry Debrosse Piano Tuning' Company in 'Indianapolis' City
2025-08-13 14:17:59 - WARNING - No Search results for Jerry Debrosse Piano Tuning, continuing to next company
2025-08-13 14:18:00 - INFO - Processing: 'Jerry L Siefers' Company in 'Bloomington' City
2025-08-13 14:18:12 - WARNING - No Search results for Jerry L Siefers, continuing to next company
2025-08-13 14:18:13 - INFO - Processing: 'Jerry Sivnksty Evangelistic' Company in 'Indianapolis' City
2025-08-13 14:18:24 - WARNING - No Search results for Jerry Sivnksty Evangelistic, continuing to next company
2025-08-13 14:18:25 - INFO - Processing: 'Jerrys Seamless Guttering' Company in 'Bloomington' City
2025-08-13 14:18:37 - WARNING - No Search results for Jerrys Seamless Guttering, continuing to next company
2025-08-13 14:18:38 - INFO - Processing: 'Jersi Shore Barber-beauty Sln' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:19:12 - INFO - Processing: 'Jerusalem Christian Ctr' Company in 'Indianapolis' City
2025-08-13 14:19:24 - WARNING - No Search results for Jerusalem Christian Ctr, continuing to next company
2025-08-13 14:19:25 - INFO - Processing: 'Jes & Sons Inc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:19:59 - INFO - Processing: 'Jessi Issa Tattoo Llc' Company in 'Indianapolis' City
2025-08-13 14:20:11 - WARNING - No Search results for Jessi Issa Tattoo Llc, continuing to next company
2025-08-13 14:20:12 - INFO - Processing: 'Jessilyn Mcmanus' Company in 'Boonville' City
2025-08-13 14:20:23 - WARNING - No Search results for Jessilyn Mcmanus, continuing to next company
2025-08-13 14:20:24 - INFO - Processing: 'Jesus Christ Worship Ctr Inc' Company in 'Indianapolis' City
2025-08-13 14:20:35 - WARNING - No Search results for Jesus Christ Worship Ctr Inc, continuing to next company
2025-08-13 14:20:36 - INFO - Processing: 'Jesus Fellowship Church' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:21:08 - INFO - Processing: 'Jesus House-prayer Temple' Company in 'Indianapolis' City
2025-08-13 14:21:19 - WARNING - No Search results for Jesus House-prayer Temple, continuing to next company
2025-08-13 14:21:20 - INFO - Processing: 'Jesus Is Lord Christian Church' Company in 'Indianapolis' City
2025-08-13 14:21:37 - INFO - ❗No matching company found for search_term: Jesus Is Lord Christian Church with search_city:Indianapolis
2025-08-13 14:21:37 - INFO - Processing: 'Jesus Is The Word Church Inc' Company in 'Indianapolis' City
2025-08-13 14:21:54 - INFO - ❗No matching company found for search_term: Jesus Is The Word Church Inc with search_city:Indianapolis
2025-08-13 14:21:55 - INFO - Processing: 'Jesus Mcc' Company in 'Indianapolis' City
2025-08-13 14:22:06 - WARNING - No Search results for Jesus Mcc, continuing to next company
2025-08-13 14:22:07 - INFO - Processing: 'Jesus Ministry' Company in 'Indianapolis' City
2025-08-13 14:22:23 - INFO - ❗No matching company found for search_term: Jesus Ministry with search_city:Indianapolis
2025-08-13 14:22:24 - INFO - Processing: 'Jesus My Fathers House-prayer' Company in 'Indianapolis' City
2025-08-13 14:22:40 - INFO - ❗No matching company found for search_term: Jesus My Fathers House-prayer with search_city:Indianapolis
2025-08-13 14:22:41 - INFO - Processing: 'Jesus The Chief Cornerstone' Company in 'Indianapolis' City
2025-08-13 14:22:52 - WARNING - No Search results for Jesus The Chief Cornerstone, continuing to next company
2025-08-13 14:22:52 - INFO - Processing: 'Jesus The Messiah Church' Company in 'Indianapolis' City
2025-08-13 14:23:09 - INFO - ❗No matching company found for search_term: Jesus The Messiah Church with search_city:Indianapolis
2025-08-13 14:23:09 - INFO - Processing: 'Jet Cleaning Svc' Company in 'Indianapolis' City
2025-08-13 14:23:21 - WARNING - No Search results for Jet Cleaning Svc, continuing to next company
2025-08-13 14:23:21 - INFO - Processing: 'Jet Linx' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:23:53 - INFO - Processing: 'Jet Star Inc' Company in 'Indianapolis' City
2025-08-13 14:24:10 - INFO - ❗No matching company found for search_term: Jet Star Inc with search_city:Indianapolis
2025-08-13 14:24:12 - INFO - Processing: 'Jet Tire Ctr' Company in 'Indianapolis' City
2025-08-13 14:24:23 - WARNING - No Search results for Jet Tire Ctr, continuing to next company
2025-08-13 14:24:23 - INFO - Processing: 'Jet Window Cleaning' Company in 'Noblesville' City

❌ Error locating company links

2025-08-13 14:24:55 - INFO - Processing: 'Jett Express Inc' Company in 'Indianapolis' City
2025-08-13 14:25:12 - INFO - ✅ Match found for: Jett Express, Inc. | City: Indianapolis | Similarity Score: 100.0
2025-08-13 14:26:01 - INFO - Processing: 'Jett Pro Line Maintenance' Company in 'Indianapolis' City
2025-08-13 14:26:18 - INFO - ✅ Match found for: Jet Pro Line Maintenance Corp | City: Indianapolis | Similarity Score: 97.95918367346938
2025-08-13 14:27:44 - INFO - Processing: 'Jett Pro Line Maintenance Inc' Company in 'Indianapolis' City
2025-08-13 14:28:01 - INFO - ✅ Match found for: Jet Pro Line Maintenance Corp | City: Indianapolis | Similarity Score: 97.95918367346938
2025-08-13 14:29:24 - INFO - Processing: 'Jetz Laundry Systems Inc' Company in 'Indianapolis' City
2025-08-13 14:29:43 - INFO - ❗No matching company found for search_term: Jetz Laundry Systems Inc with search_city:Indianapolis
2025-08-13 14:29:44 - INFO - Processing: 'Jetz Ser Co Inc' Company in 'Indianapolis' City
2025-08-13 14:29:55 - WARNING - No Search results for Jetz Ser Co Inc, continuing to next company
2025-08-13 14:29:56 - INFO - Processing: 'Jetz Service Co Inc' Company in 'Indianapolis' City
2025-08-13 14:30:14 - INFO - ❗No matching company found for search_term: Jetz Service Co Inc with search_city:Indianapolis
2025-08-13 14:30:15 - INFO - Processing: 'Jewish Community Relations' Company in 'Indianapolis' City
2025-08-13 14:30:26 - WARNING - No Search results for Jewish Community Relations, continuing to next company
2025-08-13 14:30:26 - INFO - Processing: 'Jewish Federation-greater' Company in 'Indianapolis' City
2025-08-13 14:30:37 - WARNING - No Search results for Jewish Federation-greater, continuing to next company
2025-08-13 14:30:38 - INFO - Processing: 'Jf Petroleum Group' Company in 'Indianapolis' City
2025-08-13 14:30:50 - WARNING - No Search results for Jf Petroleum Group, continuing to next company
2025-08-13 14:30:50 - INFO - Processing: 'Jfuel Center' Company in 'Indianapolis' City
2025-08-13 14:31:08 - INFO - ❗No matching company found for search_term: Jfuel Center with search_city:Indianapolis
2025-08-13 14:31:09 - INFO - Processing: 'Jfw Industries Inc' Company in 'Indianapolis' City
2025-08-13 14:31:25 - INFO - ✅ Match found for: JFW Industries, Inc. | City: Indianapolis | Similarity Score: 100.0
2025-08-13 14:32:02 - INFO - Processing: 'Jg Race Llc' Company in 'Auburn' City
2025-08-13 14:32:13 - WARNING - No Search results for Jg Race Llc, continuing to next company
2025-08-13 14:32:14 - INFO - Processing: 'Jici Construction' Company in 'Angola' City
2025-08-13 14:32:30 - INFO - ❗No matching company found for search_term: Jici Construction with search_city:Angola
2025-08-13 14:32:31 - INFO - Processing: 'Jiffy Lube' Company in 'Noblesville' City
2025-08-13 14:32:42 - WARNING - No Search results for Jiffy Lube, continuing to next company
2025-08-13 14:32:43 - INFO - Processing: 'Jiffy Lube' Company in 'Carmel' City
2025-08-13 14:32:54 - WARNING - No Search results for Jiffy Lube, continuing to next company
2025-08-13 14:32:55 - INFO - Processing: 'Jiffy Lube' Company in 'Indianapolis' City
2025-08-13 14:33:06 - WARNING - No Search results for Jiffy Lube, continuing to next company
2025-08-13 14:33:07 - INFO - Processing: 'Jiffy Lube' Company in 'Avon' City
2025-08-13 14:33:19 - WARNING - No Search results for Jiffy Lube, continuing to next company
2025-08-13 14:33:19 - INFO - Processing: 'Jiffy Lube' Company in 'Angola' City
2025-08-13 14:33:30 - WARNING - No Search results for Jiffy Lube, continuing to next company
2025-08-13 14:33:31 - INFO - Processing: 'Jiffy Lube' Company in 'Auburn' City
2025-08-13 14:33:42 - WARNING - No Search results for Jiffy Lube, continuing to next company
2025-08-13 14:33:43 - INFO - Processing: 'Jiffy Lube' Company in 'Anderson' City
2025-08-13 14:33:55 - WARNING - No Search results for Jiffy Lube, continuing to next company
2025-08-13 14:33:55 - INFO - Processing: 'Jiffy Lube' Company in 'Brownsburg' City
2025-08-13 14:34:06 - WARNING - No Search results for Jiffy Lube, continuing to next company
2025-08-13 14:34:07 - INFO - Processing: 'Jill Heath Electrolysis' Company in 'Carmel' City
2025-08-13 14:34:18 - WARNING - No Search results for Jill Heath Electrolysis, continuing to next company
2025-08-13 14:34:19 - INFO - Processing: 'Jim Coffey Construction' Company in 'Noblesville' City
2025-08-13 14:34:30 - WARNING - No Search results for Jim Coffey Construction, continuing to next company
2025-08-13 14:34:31 - INFO - Processing: 'Jim Cummings' Company in 'Indianapolis' City
2025-08-13 14:34:42 - WARNING - No Search results for Jim Cummings, continuing to next company
2025-08-13 14:34:43 - INFO - Processing: 'Jim Gem Enterprises Llc' Company in 'Indianapolis' City
2025-08-13 14:35:00 - INFO - ❗No matching company found for search_term: Jim Gem Enterprises Llc with search_city:Indianapolis
2025-08-13 14:35:00 - INFO - Processing: 'Jim Perrault Construction' Company in 'Butler' City
2025-08-13 14:35:12 - WARNING - No Search results for Jim Perrault Construction, continuing to next company
2025-08-13 14:35:12 - INFO - Processing: 'Jim Zac Salon' Company in 'Anderson' City
2025-08-13 14:35:23 - WARNING - No Search results for Jim Zac Salon, continuing to next company
2025-08-13 14:35:24 - INFO - Processing: 'Jimco Engineering' Company in 'Indianapolis' City
2025-08-13 14:35:42 - INFO - ❗No matching company found for search_term: Jimco Engineering with search_city:Indianapolis
2025-08-13 14:35:43 - INFO - Processing: 'Jimelle Inc' Company in 'Auburn' City
2025-08-13 14:35:54 - WARNING - No Search results for Jimelle Inc, continuing to next company
2025-08-13 14:35:55 - INFO - Processing: 'Jimmy Auto Svc' Company in 'Indianapolis' City
2025-08-13 14:36:06 - WARNING - No Search results for Jimmy Auto Svc, continuing to next company
2025-08-13 14:36:07 - INFO - Processing: 'Jimmy Buff-its Auto Detailing' Company in 'Indianapolis' City
2025-08-13 14:36:24 - INFO - ❗No matching company found for search_term: Jimmy Buff-its Auto Detailing with search_city:Indianapolis
2025-08-13 14:36:25 - INFO - Processing: 'Jims Auto Repair' Company in 'Auburn' City
2025-08-13 14:36:36 - WARNING - No Search results for Jims Auto Repair, continuing to next company
2025-08-13 14:36:37 - INFO - Processing: 'Jims Clearmount Plastic Pipe' Company in 'Avon' City
2025-08-13 14:36:48 - WARNING - No Search results for Jims Clearmount Plastic Pipe, continuing to next company
2025-08-13 14:36:49 - INFO - Processing: 'Jims Garage' Company in 'Beech Grove' City
2025-08-13 14:37:00 - WARNING - No Search results for Jims Garage, continuing to next company
2025-08-13 14:37:00 - INFO - Processing: 'Jims Motor Sales & Svc' Company in 'Anderson' City
2025-08-13 14:37:12 - WARNING - No Search results for Jims Motor Sales & Svc, continuing to next company
2025-08-13 14:37:13 - INFO - Processing: 'Jims Super Clean' Company in 'Highland' City
2025-08-13 14:37:31 - INFO - ❗No matching company found for search_term: Jims Super Clean with search_city:Highland
2025-08-13 14:37:32 - INFO - Processing: 'Jims Tree Experts' Company in 'Indianapolis' City
2025-08-13 14:37:43 - WARNING - No Search results for Jims Tree Experts, continuing to next company
2025-08-13 14:37:44 - INFO - Processing: 'Jimzac Hair Co' Company in 'Anderson' City
2025-08-13 14:37:55 - WARNING - No Search results for Jimzac Hair Co, continuing to next company
2025-08-13 14:37:56 - INFO - Processing: 'Jins Corner' Company in 'Indianapolis' City
2025-08-13 14:38:07 - WARNING - No Search results for Jins Corner, continuing to next company
2025-08-13 14:38:08 - INFO - Processing: 'Jireh Barber Shop & Salon Llc' Company in 'Indianapolis' City
2025-08-13 14:38:19 - WARNING - No Search results for Jireh Barber Shop & Salon Llc, continuing to next company
2025-08-13 14:38:20 - INFO - Processing: 'Jist Transportation Llc' Company in 'Indianapolis' City
2025-08-13 14:38:38 - INFO - ❗No matching company found for search_term: Jist Transportation Llc with search_city:Indianapolis
2025-08-13 14:38:38 - INFO - Processing: 'Jivansandhya Inc' Company in 'Bloomington' City
2025-08-13 14:38:50 - WARNING - No Search results for Jivansandhya Inc, continuing to next company
2025-08-13 14:38:50 - INFO - Processing: 'Jiyane Freight Lines Llc' Company in 'Indianapolis' City
2025-08-13 14:39:08 - INFO - ❗No matching company found for search_term: Jiyane Freight Lines Llc with search_city:Indianapolis
2025-08-13 14:39:11 - INFO - Processing: 'Jjk Builders Inc' Company in 'Alexandria' City
2025-08-13 14:39:23 - WARNING - No Search results for Jjk Builders Inc, continuing to next company
2025-08-13 14:39:24 - INFO - Processing: 'Jjs Spa' Company in 'Brownsburg' City

❌ Error locating company links

2025-08-13 14:39:58 - INFO - Processing: 'Jjt Dispatch & Logistics Llc' Company in 'Indianapolis' City
2025-08-13 14:40:10 - WARNING - No Search results for Jjt Dispatch & Logistics Llc, continuing to next company
2025-08-13 14:40:11 - INFO - Processing: 'Jl Construction' Company in 'Bristol' City
2025-08-13 14:40:29 - INFO - ❗No matching company found for search_term: Jl Construction with search_city:Bristol
2025-08-13 14:40:30 - INFO - Processing: 'Jl Goshen-ppe Supplies Llc' Company in 'Indianapolis' City
2025-08-13 14:40:49 - INFO - ❗No matching company found for search_term: Jl Goshen-ppe Supplies Llc with search_city:Indianapolis
2025-08-13 14:40:50 - INFO - Processing: 'Jl Squared Inc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:41:24 - INFO - Processing: 'Jlp Logistics' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:41:59 - INFO - Processing: 'Jm Construction' Company in 'Indianapolis' City
2025-08-13 14:42:17 - INFO - ❗No matching company found for search_term: Jm Construction with search_city:Indianapolis
2025-08-13 14:42:18 - INFO - Processing: 'Jmb Llc' Company in 'Beech Grove' City

❌ Error locating company links

2025-08-13 14:42:56 - INFO - Processing: 'JMC' Company in 'Indianapolis' City
2025-08-13 14:43:15 - INFO - ❗No matching company found for search_term: JMC with search_city:Indianapolis
2025-08-13 14:43:16 - INFO - Processing: 'Jmc Concrete Solution Llc' Company in 'Indianapolis' City
2025-08-13 14:43:35 - INFO - ❗No matching company found for search_term: Jmc Concrete Solution Llc with search_city:Indianapolis
2025-08-13 14:43:35 - INFO - Processing: 'Jmc Sales & Engineering' Company in 'Indianapolis' City
2025-08-13 14:43:54 - INFO - ✅ Match found for: Jmc Sales And Engineering, Inc. | City: Indianapolis | Similarity Score: 91.30434782608697
2025-08-13 14:45:06 - INFO - Processing: 'Jmd Usa Inc' Company in 'Indianapolis' City
2025-08-13 14:45:18 - WARNING - No Search results for Jmd Usa Inc, continuing to next company
2025-08-13 14:45:19 - INFO - Processing: 'Jme Enterprises Inc' Company in 'Indianapolis' City
2025-08-13 14:45:38 - INFO - ❗No matching company found for search_term: Jme Enterprises Inc with search_city:Indianapolis
2025-08-13 14:45:39 - INFO - Processing: 'Jmg Products Inc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:46:13 - INFO - Processing: 'Jmh Roofing' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:46:47 - INFO - Processing: 'Jmi Mechanical' Company in 'Indianapolis' City
2025-08-13 14:47:05 - INFO - ❗No matching company found for search_term: Jmi Mechanical with search_city:Indianapolis
2025-08-13 14:47:06 - INFO - Processing: 'Jmj Petroleum' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:47:40 - INFO - Processing: 'Jmkshair' Company in 'Indianapolis' City
2025-08-13 14:47:53 - WARNING - No Search results for Jmkshair, continuing to next company
2025-08-13 14:47:54 - INFO - Processing: 'Jmr General Cntrctng-handyman' Company in 'Indianapolis' City
2025-08-13 14:48:06 - WARNING - No Search results for Jmr General Cntrctng-handyman, continuing to next company
2025-08-13 14:48:07 - INFO - Processing: 'Jms Industries Llc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:48:42 - INFO - Processing: 'Jn Tiling & Construction' Company in 'Angola' City

❌ Error locating company links

2025-08-13 14:49:16 - INFO - Processing: 'Joans' Company in 'Batesville' City
2025-08-13 14:49:34 - INFO - ❗No matching company found for search_term: Joans with search_city:Batesville
2025-08-13 14:49:35 - INFO - Processing: 'Joans T-shirt Printing' Company in 'Batesville' City
2025-08-13 14:49:55 - INFO - ❗No matching company found for search_term: Joans T-shirt Printing with search_city:Batesville
2025-08-13 14:49:56 - INFO - Processing: 'Job Accommodations Inc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:50:31 - INFO - Processing: 'Job News-indianapolis' Company in 'Indianapolis' City
2025-08-13 14:50:50 - INFO - ❗No matching company found for search_term: Job News-indianapolis with search_city:Indianapolis
2025-08-13 14:50:51 - INFO - Processing: 'Job Works' Company in 'Indianapolis' City
2025-08-13 14:51:10 - INFO - ❗No matching company found for search_term: Job Works with search_city:Indianapolis
2025-08-13 14:51:11 - INFO - Processing: 'Jobsite Supply' Company in 'Indianapolis' City
2025-08-13 14:51:30 - INFO - ❗No matching company found for search_term: Jobsite Supply with search_city:Indianapolis
2025-08-13 14:51:31 - INFO - Processing: 'Jobsource Inc' Company in 'Anderson' City

❌ Error locating company links

2025-08-13 14:52:06 - INFO - Processing: 'Joe G Painting' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:52:40 - INFO - Processing: 'Joe G Painting' Company in 'Carmel' City

❌ Error locating company links

2025-08-13 14:53:15 - INFO - Processing: 'Joe H Construction Inc' Company in 'Berne' City
2025-08-13 14:53:34 - INFO - ❗No matching company found for search_term: Joe H Construction Inc with search_city:Berne
2025-08-13 14:53:35 - INFO - Processing: 'Joe Hubers Family Farm-rstrnt' Company in 'Borden' City
2025-08-13 14:53:54 - INFO - ❗No matching company found for search_term: Joe Hubers Family Farm-rstrnt with search_city:Borden
2025-08-13 14:53:55 - INFO - Processing: 'Joe Lannan Excavtg Rock-stone' Company in 'Linton' City
2025-08-13 14:54:07 - WARNING - No Search results for Joe Lannan Excavtg Rock-stone, continuing to next company
2025-08-13 14:54:12 - INFO - Processing: 'Joe Schmo Inc' Company in 'Indianapolis' City
2025-08-13 14:54:24 - WARNING - No Search results for Joe Schmo Inc, continuing to next company
2025-08-13 14:54:25 - INFO - Processing: 'Joel Cohen Group Llc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:54:59 - INFO - Processing: 'Joes Auto Svc' Company in 'Noblesville' City
2025-08-13 14:55:12 - WARNING - No Search results for Joes Auto Svc, continuing to next company
2025-08-13 14:55:13 - INFO - Processing: 'Joes Barber Shop' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:55:47 - INFO - Processing: 'Joes Cuts' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:56:21 - INFO - Processing: 'Joes Express Towing' Company in 'Indianapolis' City
2025-08-13 14:56:33 - WARNING - No Search results for Joes Express Towing, continuing to next company
2025-08-13 14:56:34 - INFO - Processing: 'Joes Garage & Whitlows Towing' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 14:57:08 - INFO - Processing: 'Joes Garage 317 Llc' Company in 'Noblesville' City

❌ Error locating company links

2025-08-13 14:57:42 - INFO - Processing: 'Joes Service Dept' Company in 'Indianapolis' City
2025-08-13 14:58:03 - INFO - ❗No matching company found for search_term: Joes Service Dept with search_city:Indianapolis
2025-08-13 14:58:06 - INFO - Processing: 'Joes Tattoo Parlour' Company in 'Bargersville' City
2025-08-13 14:58:19 - WARNING - No Search results for Joes Tattoo Parlour, continuing to next company
2025-08-13 14:58:20 - INFO - Processing: 'Joes Value Construction' Company in 'Indianapolis' City
2025-08-13 14:58:32 - WARNING - No Search results for Joes Value Construction, continuing to next company
2025-08-13 14:58:33 - INFO - Processing: 'Joey C Construction Llc' Company in 'Indianapolis' City
2025-08-13 14:58:52 - INFO - ❗No matching company found for search_term: Joey C Construction Llc with search_city:Indianapolis
2025-08-13 14:58:52 - INFO - Processing: 'Joey D Auler Builders' Company in 'Anderson' City
2025-08-13 14:59:12 - INFO - ❗No matching company found for search_term: Joey D Auler Builders with search_city:Anderson
2025-08-13 14:59:13 - INFO - Processing: 'John A Hillenbrand Foundation' Company in 'Batesville' City
2025-08-13 14:59:32 - INFO - ❗No matching company found for search_term: John A Hillenbrand Foundation with search_city:Batesville
2025-08-13 14:59:33 - INFO - Processing: 'John Arnold Constr & Excavtg' Company in 'Bloomfield' City
2025-08-13 14:59:45 - WARNING - No Search results for John Arnold Constr & Excavtg, continuing to next company
2025-08-13 14:59:46 - INFO - Processing: 'John Ault Farms' Company in 'Akron' City
2025-08-13 14:59:58 - WARNING - No Search results for John Ault Farms, continuing to next company
2025-08-13 14:59:59 - INFO - Processing: 'John Deering Cleaners' Company in 'Indianapolis' City
2025-08-13 15:00:11 - WARNING - No Search results for John Deering Cleaners, continuing to next company
2025-08-13 15:00:12 - INFO - Processing: 'John Fowler Plumbing' Company in 'Indianapolis' City
2025-08-13 15:00:24 - WARNING - No Search results for John Fowler Plumbing, continuing to next company
2025-08-13 15:00:25 - INFO - Processing: 'John Frick & Assoc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:00:59 - INFO - Processing: 'John Glenn Band Boosters Inc' Company in 'Walkerton' City
2025-08-13 15:01:17 - INFO - ❗No matching company found for search_term: John Glenn Band Boosters Inc with search_city:Walkerton
2025-08-13 15:01:18 - INFO - Processing: 'John Hillenbrand Office' Company in 'Batesville' City
2025-08-13 15:01:30 - WARNING - No Search results for John Hillenbrand Office, continuing to next company
2025-08-13 15:01:31 - INFO - Processing: 'John Ingram Builder Inc' Company in 'Bloomington' City

❌ Error locating company links

2025-08-13 15:02:06 - INFO - Processing: 'John Knox Presbyterian Church' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:02:40 - INFO - Processing: 'John Ley Monument Sales' Company in 'Avilla' City
2025-08-13 15:02:52 - WARNING - No Search results for John Ley Monument Sales, continuing to next company
2025-08-13 15:02:53 - INFO - Processing: 'John Mark Fisher Tree Svc' Company in 'Bloomington' City
2025-08-13 15:03:05 - WARNING - No Search results for John Mark Fisher Tree Svc, continuing to next company
2025-08-13 15:03:06 - INFO - Processing: 'John Naylor Trucking' Company in 'Bloomington' City
2025-08-13 15:03:18 - WARNING - No Search results for John Naylor Trucking, continuing to next company
2025-08-13 15:03:19 - INFO - Processing: 'John Padgett Cstm Interior' Company in 'Indianapolis' City
2025-08-13 15:03:31 - WARNING - No Search results for John Padgett Cstm Interior, continuing to next company
2025-08-13 15:03:31 - INFO - Processing: 'John Peters Roofing' Company in 'Indianapolis' City
2025-08-13 15:03:43 - WARNING - No Search results for John Peters Roofing, continuing to next company
2025-08-13 15:03:44 - INFO - Processing: 'John S Massey' Company in 'Auburn' City
2025-08-13 15:04:04 - INFO - ❗No matching company found for search_term: John S Massey with search_city:Auburn
2025-08-13 15:04:05 - INFO - Processing: 'John The Builder Llc' Company in 'Arcadia' City
2025-08-13 15:04:25 - INFO - ❗No matching company found for search_term: John The Builder Llc with search_city:Arcadia
2025-08-13 15:04:26 - INFO - Processing: 'John Wesley Free Methodist Chr' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:05:00 - INFO - Processing: 'John Young Painting' Company in 'Angola' City
2025-08-13 15:05:13 - WARNING - No Search results for John Young Painting, continuing to next company
2025-08-13 15:05:14 - INFO - Processing: 'John-joan Hillenbrand Vision' Company in 'Batesville' City
2025-08-13 15:05:32 - INFO - ❗No matching company found for search_term: John-joan Hillenbrand Vision with search_city:Batesville
2025-08-13 15:05:33 - INFO - Processing: 'Johnny Lemas Fireworks' Company in 'Angola' City
2025-08-13 15:05:46 - WARNING - No Search results for Johnny Lemas Fireworks, continuing to next company
2025-08-13 15:05:47 - INFO - Processing: 'Johnny Miller Trnsprtn & Tours' Company in 'Aurora' City
2025-08-13 15:05:59 - WARNING - No Search results for Johnny Miller Trnsprtn & Tours, continuing to next company
2025-08-13 15:06:00 - INFO - Processing: 'Johnnys Pest Elimination Svc' Company in 'Linton' City
2025-08-13 15:06:12 - WARNING - No Search results for Johnnys Pest Elimination Svc, continuing to next company
2025-08-13 15:06:13 - INFO - Processing: 'Johnnys Roofing' Company in 'Argos' City

❌ Error locating company links

2025-08-13 15:06:47 - INFO - Processing: 'Johnnys Signs Inc' Company in 'Bedford' City
2025-08-13 15:07:05 - INFO - ❗No matching company found for search_term: Johnnys Signs Inc with search_city:Bedford
2025-08-13 15:07:06 - INFO - Processing: 'Johnnys Tip Top Barbershop' Company in 'Bremen' City
2025-08-13 15:07:18 - WARNING - No Search results for Johnnys Tip Top Barbershop, continuing to next company
2025-08-13 15:07:20 - INFO - Processing: 'Johns Automotive' Company in 'Indianapolis' City
2025-08-13 15:07:38 - INFO - ❗No matching company found for search_term: Johns Automotive with search_city:Indianapolis
2025-08-13 15:07:39 - INFO - Processing: 'Johns Drain Cleaning Svc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:08:13 - INFO - Processing: 'Johns Manville' Company in 'Bremen' City

❌ Error locating company links

2025-08-13 15:08:48 - INFO - Processing: 'Johns Poultry Co' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:09:25 - INFO - Processing: 'Johns Sewer & Drain Cleaning' Company in 'Boonville' City
2025-08-13 15:09:42 - INFO - ❗No matching company found for search_term: Johns Sewer & Drain Cleaning with search_city:Boonville
2025-08-13 15:09:43 - INFO - Processing: 'Johns Sewer & Drain Svc' Company in 'Indianapolis' City
2025-08-13 15:10:02 - INFO - ❗No matching company found for search_term: Johns Sewer & Drain Svc with search_city:Indianapolis
2025-08-13 15:10:03 - INFO - Processing: 'Johnson Cleaning Svc' Company in 'Cedar Lake' City
2025-08-13 15:10:15 - WARNING - No Search results for Johnson Cleaning Svc, continuing to next company
2025-08-13 15:10:16 - INFO - Processing: 'Johnson Commercial Flooring' Company in 'Indianapolis' City
2025-08-13 15:10:34 - INFO - ❗No matching company found for search_term: Johnson Commercial Flooring with search_city:Indianapolis
2025-08-13 15:10:35 - INFO - Processing: 'Johnson Construction' Company in 'Indianapolis' City
2025-08-13 15:10:54 - INFO - ❗No matching company found for search_term: Johnson Construction with search_city:Indianapolis
2025-08-13 15:10:55 - INFO - Processing: 'Johnson Controls' Company in 'Indianapolis' City
2025-08-13 15:11:14 - INFO - ❗No matching company found for search_term: Johnson Controls with search_city:Indianapolis
2025-08-13 15:11:15 - INFO - Processing: 'Johnson Controls Fire Protctn' Company in 'Indianapolis' City
2025-08-13 15:11:34 - INFO - ❗No matching company found for search_term: Johnson Controls Fire Protctn with search_city:Indianapolis
2025-08-13 15:11:35 - INFO - Processing: 'Johnson Electric' Company in 'Indianapolis' City
2025-08-13 15:11:55 - INFO - ❗No matching company found for search_term: Johnson Electric with search_city:Indianapolis
2025-08-13 15:11:56 - INFO - Processing: 'Johnson Funeral Home' Company in 'Butler' City
2025-08-13 15:12:17 - INFO - ❗No matching company found for search_term: Johnson Funeral Home with search_city:Butler
2025-08-13 15:12:18 - INFO - Processing: 'Johnson Glen David' Company in 'Avon' City
2025-08-13 15:12:30 - WARNING - No Search results for Johnson Glen David, continuing to next company
2025-08-13 15:12:32 - INFO - Processing: 'Johnson Specialized Transport' Company in 'Auburn' City

❌ Error locating company links

2025-08-13 15:13:08 - INFO - Processing: 'Johnson-melloh Solutions' Company in 'Indianapolis' City
2025-08-13 15:13:26 - INFO - ❗No matching company found for search_term: Johnson-melloh Solutions with search_city:Indianapolis
2025-08-13 15:13:28 - INFO - Processing: 'Johnsons Hauling & Excavating' Company in 'Bargersville' City
2025-08-13 15:13:46 - INFO - ❗No matching company found for search_term: Johnsons Hauling & Excavating with search_city:Bargersville
2025-08-13 15:13:47 - INFO - Processing: 'Johnsons Repair' Company in 'Indianapolis' City
2025-08-13 15:14:06 - INFO - ❗No matching company found for search_term: Johnsons Repair with search_city:Indianapolis
2025-08-13 15:14:07 - INFO - Processing: 'Johnsons Tree Svc' Company in 'Indianapolis' City
2025-08-13 15:14:19 - WARNING - No Search results for Johnsons Tree Svc, continuing to next company
2025-08-13 15:14:20 - INFO - Processing: 'Johnstone Supply' Company in 'Indianapolis' City
2025-08-13 15:14:40 - INFO - ❗No matching company found for search_term: Johnstone Supply with search_city:Indianapolis
2025-08-13 15:14:41 - INFO - Processing: 'Joint Industry Affairs Llc' Company in 'Brookville' City
2025-08-13 15:15:00 - INFO - ❗No matching company found for search_term: Joint Industry Affairs Llc with search_city:Brookville
2025-08-13 15:15:01 - INFO - Processing: 'Jokerr Fabrication Llc' Company in 'Brownsburg' City
2025-08-13 15:15:13 - WARNING - No Search results for Jokerr Fabrication Llc, continuing to next company
2025-08-13 15:15:15 - INFO - Processing: 'Joma Leonardo Meml Fund Inc' Company in 'Indianapolis' City
2025-08-13 15:15:27 - WARNING - No Search results for Joma Leonardo Meml Fund Inc, continuing to next company
2025-08-13 15:15:28 - INFO - Processing: 'Jon Potter Scholarship Fund' Company in 'Avon' City
2025-08-13 15:15:40 - WARNING - No Search results for Jon Potter Scholarship Fund, continuing to next company
2025-08-13 15:15:41 - INFO - Processing: 'Jonahs Automotive-sm Eng Rpr' Company in 'Walkerton' City
2025-08-13 15:15:53 - WARNING - No Search results for Jonahs Automotive-sm Eng Rpr, continuing to next company
2025-08-13 15:15:54 - INFO - Processing: 'Jonco Co Inc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:16:29 - INFO - Processing: 'Joneco Systems' Company in 'Indianapolis' City
2025-08-13 15:16:50 - INFO - ❗No matching company found for search_term: Joneco Systems with search_city:Indianapolis
2025-08-13 15:16:51 - INFO - Processing: 'Jones & Jones Janitorial Llc' Company in 'Indianapolis' City
2025-08-13 15:17:12 - INFO - ❗No matching company found for search_term: Jones & Jones Janitorial Llc with search_city:Indianapolis
2025-08-13 15:17:13 - INFO - Processing: 'Jones & Laughlin Steel Svc Ctr' Company in 'Indianapolis' City
2025-08-13 15:17:35 - INFO - ❗No matching company found for search_term: Jones & Laughlin Steel Svc Ctr with search_city:Indianapolis
2025-08-13 15:17:36 - INFO - Processing: 'Jones Auto Mechanic Llc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:18:10 - INFO - Processing: 'Jones Bros Llc' Company in 'Noblesville' City
2025-08-13 15:18:29 - INFO - ❗No matching company found for search_term: Jones Bros Llc with search_city:Noblesville
2025-08-13 15:18:29 - INFO - Processing: 'Jones Brothers Electric' Company in 'Indianapolis' City
2025-08-13 15:18:49 - INFO - ❗No matching company found for search_term: Jones Brothers Electric with search_city:Indianapolis
2025-08-13 15:18:50 - INFO - Processing: 'Jones Commercial Interiors' Company in 'Berne' City

❌ Error locating company links

2025-08-13 15:19:25 - INFO - Processing: 'Jones Concrete Lifting-ground' Company in 'Aurora' City

❌ Error locating company links

2025-08-13 15:19:59 - INFO - Processing: 'Jones Fish Hatchery' Company in 'Indianapolis' City
2025-08-13 15:20:17 - INFO - ❗No matching company found for search_term: Jones Fish Hatchery with search_city:Indianapolis
2025-08-13 15:20:18 - INFO - Processing: 'Jones Homes & Renovations Llc' Company in 'Attica' City
2025-08-13 15:20:39 - INFO - ❗No matching company found for search_term: Jones Homes & Renovations Llc with search_city:Attica
2025-08-13 15:20:40 - INFO - Processing: 'Jones Motor' Company in 'Bristol' City
2025-08-13 15:20:59 - INFO - ❗No matching company found for search_term: Jones Motor with search_city:Bristol
2025-08-13 15:21:00 - INFO - Processing: 'Jones Movers Inc' Company in 'Indianapolis' City
2025-08-13 15:21:12 - WARNING - No Search results for Jones Movers Inc, continuing to next company
2025-08-13 15:21:13 - INFO - Processing: 'Jones Painting' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:21:47 - INFO - Processing: 'Jones Tabernacle Ame Zion Chr' Company in 'Indianapolis' City
2025-08-13 15:22:00 - WARNING - No Search results for Jones Tabernacle Ame Zion Chr, continuing to next company
2025-08-13 15:22:01 - INFO - Processing: 'Jones Variety Shop' Company in 'Bedford' City

❌ Error locating company links

2025-08-13 15:22:34 - INFO - Processing: 'Jons Air' Company in 'Carmel' City

❌ Error locating company links

2025-08-13 15:23:09 - INFO - Processing: 'Jons Transmission Svc' Company in 'Alexandria' City
2025-08-13 15:23:21 - WARNING - No Search results for Jons Transmission Svc, continuing to next company
2025-08-13 15:23:22 - INFO - Processing: 'Jordan & Assoc Llc' Company in 'Indianapolis' City
2025-08-13 15:23:41 - INFO - ❗No matching company found for search_term: Jordan & Assoc Llc with search_city:Indianapolis
2025-08-13 15:23:42 - INFO - Processing: 'Jordans Fish Chicken & Gyros' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:24:17 - INFO - Processing: 'Jorge & Assoc Construction Llc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:24:55 - INFO - Processing: 'Jos Salvage Cash For Cars' Company in 'Indianapolis' City
2025-08-13 15:25:14 - INFO - ❗No matching company found for search_term: Jos Salvage Cash For Cars with search_city:Indianapolis
2025-08-13 15:25:15 - INFO - Processing: 'Jose Arroyo Construction' Company in 'Indianapolis' City
2025-08-13 15:25:27 - WARNING - No Search results for Jose Arroyo Construction, continuing to next company
2025-08-13 15:25:28 - INFO - Processing: 'Joseph T Ryerson & Son Inc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:26:03 - INFO - Processing: 'Josh Hayes Construction Co' Company in 'Avon' City

❌ Error locating company links

2025-08-13 15:26:37 - INFO - Processing: 'Josh Hubbell Evangelistic' Company in 'Linton' City
2025-08-13 15:26:49 - WARNING - No Search results for Josh Hubbell Evangelistic, continuing to next company
2025-08-13 15:26:50 - INFO - Processing: 'Joshua Fund' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:27:24 - INFO - Processing: 'Journey Church' Company in 'Avon' City

❌ Error locating company links

2025-08-13 15:27:59 - INFO - Processing: 'Journey Church Of Brownsburg' Company in 'Brownsburg' City
2025-08-13 15:28:19 - INFO - ❗No matching company found for search_term: Journey Church Of Brownsburg with search_city:Brownsburg
2025-08-13 15:28:21 - INFO - Processing: 'Journey Church Of Christ' Company in 'Anderson' City
2025-08-13 15:28:42 - INFO - ❗No matching company found for search_term: Journey Church Of Christ with search_city:Anderson
2025-08-13 15:28:43 - INFO - Processing: 'Journey Of Hope' Company in 'Indianapolis' City
2025-08-13 15:29:03 - INFO - ❗No matching company found for search_term: Journey Of Hope with search_city:Indianapolis
2025-08-13 15:29:04 - INFO - Processing: 'Journey Rd Treatment Ctr' Company in 'Indianapolis' City
2025-08-13 15:29:17 - WARNING - No Search results for Journey Rd Treatment Ctr, continuing to next company
2025-08-13 15:29:18 - INFO - Processing: 'Jovannis Painting Llc' Company in 'Attica' City
2025-08-13 15:29:30 - WARNING - No Search results for Jovannis Painting Llc, continuing to next company
2025-08-13 15:29:31 - INFO - Processing: 'Jovie Of Greater Indianapolis' Company in 'Carmel' City
2025-08-13 15:29:52 - INFO - ❗No matching company found for search_term: Jovie Of Greater Indianapolis with search_city:Carmel
2025-08-13 15:29:53 - INFO - Processing: 'Joy Alterations' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:30:27 - INFO - Processing: 'Joy Baptist Church' Company in 'Indianapolis' City
2025-08-13 15:30:39 - WARNING - No Search results for Joy Baptist Church, continuing to next company
2025-08-13 15:30:40 - INFO - Processing: 'Joy Corp' Company in 'Indianapolis' City
2025-08-13 15:30:59 - INFO - ❗No matching company found for search_term: Joy Corp with search_city:Indianapolis
2025-08-13 15:31:00 - INFO - Processing: 'Joy Of All Who Sorrow' Company in 'Indianapolis' City
2025-08-13 15:31:21 - INFO - ❗No matching company found for search_term: Joy Of All Who Sorrow with search_city:Indianapolis
2025-08-13 15:31:22 - INFO - Processing: 'Joy Of The Lord Church Inc' Company in 'Indianapolis' City
2025-08-13 15:31:42 - INFO - ❗No matching company found for search_term: Joy Of The Lord Church Inc with search_city:Indianapolis
2025-08-13 15:31:43 - INFO - Processing: 'Joyner Construction' Company in 'Avon' City

❌ Error locating company links

2025-08-13 15:32:18 - INFO - Processing: 'Jp Lahr & Sons Roofing Svc Inc' Company in 'Indianapolis' City
2025-08-13 15:32:31 - WARNING - No Search results for Jp Lahr & Sons Roofing Svc Inc, continuing to next company
2025-08-13 15:32:32 - INFO - Processing: 'Jpf Properties Llc' Company in 'Bloomington' City

❌ Error locating company links

2025-08-13 15:33:06 - INFO - Processing: 'Jrf Construction' Company in 'Carmel' City
2025-08-13 15:33:24 - INFO - ❗No matching company found for search_term: Jrf Construction with search_city:Carmel
2025-08-13 15:33:25 - INFO - Processing: 'Jrg Materials Llc' Company in 'Brazil' City
2025-08-13 15:33:44 - INFO - ✅ Match found for: Jrg Materials Llc | City: Brazil | Similarity Score: 100.0
2025-08-13 15:35:27 - INFO - Processing: 'Jrh Renovations Llc' Company in 'Indianapolis' City
2025-08-13 15:35:39 - WARNING - No Search results for Jrh Renovations Llc, continuing to next company
2025-08-13 15:35:40 - INFO - Processing: 'Jrp Machine Co' Company in 'Indianapolis' City
2025-08-13 15:36:00 - INFO - ❗No matching company found for search_term: Jrp Machine Co with search_city:Indianapolis
2025-08-13 15:36:02 - INFO - Processing: 'Jrs Cleaning Svc' Company in 'Indianapolis' City
2025-08-13 15:36:14 - WARNING - No Search results for Jrs Cleaning Svc, continuing to next company
2025-08-13 15:36:15 - INFO - Processing: 'Jrs Construction Group Llc' Company in 'Indianapolis' City
2025-08-13 15:36:35 - INFO - ❗No matching company found for search_term: Jrs Construction Group Llc with search_city:Indianapolis
2025-08-13 15:36:36 - INFO - Processing: 'Jrs Custom Fabrication' Company in 'Brownsburg' City

❌ Error locating company links

2025-08-13 15:37:10 - INFO - Processing: 'Jrs Services & Recovery Llc' Company in 'Indianapolis' City
2025-08-13 15:37:32 - INFO - ❗No matching company found for search_term: Jrs Services & Recovery Llc with search_city:Indianapolis
2025-08-13 15:37:33 - INFO - Processing: 'J-rs Used Tires' Company in 'Indianapolis' City
2025-08-13 15:37:51 - INFO - ❗No matching company found for search_term: J-rs Used Tires with search_city:Indianapolis
2025-08-13 15:37:53 - INFO - Processing: 'Js Automotive Inc' Company in 'Avon' City
2025-08-13 15:38:11 - INFO - ❗No matching company found for search_term: Js Automotive Inc with search_city:Avon
2025-08-13 15:38:12 - INFO - Processing: 'Js Barber Shop' Company in 'Highland' City

❌ Error locating company links

2025-08-13 15:38:46 - INFO - Processing: 'Js Flooring Svc' Company in 'Indianapolis' City
2025-08-13 15:38:59 - WARNING - No Search results for Js Flooring Svc, continuing to next company
2025-08-13 15:39:00 - INFO - Processing: 'Js Ibrows & Spa' Company in 'Indianapolis' City
2025-08-13 15:39:12 - WARNING - No Search results for Js Ibrows & Spa, continuing to next company
2025-08-13 15:39:13 - INFO - Processing: 'Jt Alterations' Company in 'Indianapolis' City
2025-08-13 15:39:25 - WARNING - No Search results for Jt Alterations, continuing to next company
2025-08-13 15:39:26 - INFO - Processing: 'Jtb Concrete Inc' Company in 'Linton' City

❌ Error locating company links

2025-08-13 15:40:03 - INFO - Processing: 'Jtb Trucking Llc' Company in 'Indianapolis' City
2025-08-13 15:40:15 - WARNING - No Search results for Jtb Trucking Llc, continuing to next company
2025-08-13 15:40:16 - INFO - Processing: 'Jtj Group' Company in 'Carmel' City

❌ Error locating company links

2025-08-13 15:40:51 - INFO - Processing: 'Jtm Auto Care' Company in 'Indianapolis' City
2025-08-13 15:41:11 - INFO - ❗No matching company found for search_term: Jtm Auto Care with search_city:Indianapolis
2025-08-13 15:41:12 - INFO - Processing: 'Jts Service' Company in 'Indianapolis' City
2025-08-13 15:41:33 - INFO - ❗No matching company found for search_term: Jts Service with search_city:Indianapolis
2025-08-13 15:41:34 - INFO - Processing: 'Jubilee Harvest Christian Ctr' Company in 'Bloomington' City
2025-08-13 15:41:46 - WARNING - No Search results for Jubilee Harvest Christian Ctr, continuing to next company
2025-08-13 15:41:47 - INFO - Processing: 'Jud Scott Consuting Arborist' Company in 'Carmel' City
2025-08-13 15:42:00 - WARNING - No Search results for Jud Scott Consuting Arborist, continuing to next company
2025-08-13 15:42:01 - INFO - Processing: 'Judy Ayers Flowers Wholesale' Company in 'Indianapolis' City
2025-08-13 15:42:13 - WARNING - No Search results for Judy Ayers Flowers Wholesale, continuing to next company
2025-08-13 15:42:14 - INFO - Processing: 'Julian Earthwork Inc' Company in 'Angola' City

❌ Error locating company links

2025-08-13 15:42:47 - INFO - Processing: 'Julie Todd Cleaning Llc' Company in 'Bloomington' City
2025-08-13 15:43:00 - WARNING - No Search results for Julie Todd Cleaning Llc, continuing to next company
2025-08-13 15:43:01 - INFO - Processing: 'Julius Automotive Inc' Company in 'Indianapolis' City
2025-08-13 15:43:13 - WARNING - No Search results for Julius Automotive Inc, continuing to next company
2025-08-13 15:43:14 - INFO - Processing: 'Jump In Style' Company in 'Brookville' City

❌ Error locating company links

2025-08-13 15:43:49 - INFO - Processing: 'Jump Laundry' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:44:23 - INFO - Processing: 'Jumpin For Jazz' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:44:58 - INFO - Processing: 'Jumpstart Child Care Ministry' Company in 'Indianapolis' City
2025-08-13 15:45:18 - INFO - ❗No matching company found for search_term: Jumpstart Child Care Ministry with search_city:Indianapolis
2025-08-13 15:45:19 - INFO - Processing: 'Jungclaus Campbell Co Inc' Company in 'Indianapolis' City
2025-08-13 15:45:38 - INFO - ❗No matching company found for search_term: Jungclaus Campbell Co Inc with search_city:Indianapolis
2025-08-13 15:45:39 - INFO - Processing: 'Junior Achievement Central' Company in 'Indianapolis' City
2025-08-13 15:45:58 - INFO - ✅ Match found for: Junior Achievement Of Central Indiana, Inc. | City: Indianapolis | Similarity Score: 82.53968253968253
2025-08-13 15:47:38 - INFO - Processing: 'Junior League Of Indianapolis' Company in 'Indianapolis' City
2025-08-13 15:47:59 - INFO - ❗No matching company found for search_term: Junior League Of Indianapolis with search_city:Indianapolis
2025-08-13 15:48:00 - INFO - Processing: 'Juniors Transport Llc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:48:34 - INFO - Processing: 'Junki Virgin Hair Llc' Company in 'Indianapolis' City
2025-08-13 15:48:52 - INFO - ❗No matching company found for search_term: Junki Virgin Hair Llc with search_city:Indianapolis
2025-08-13 15:48:54 - INFO - Processing: 'Just A Little Off Hair Salon' Company in 'Cambridge City' City
2025-08-13 15:49:13 - INFO - ❗No matching company found for search_term: Just A Little Off Hair Salon with search_city:Cambridge City
2025-08-13 15:49:14 - INFO - Processing: 'Just Add Storage Llc' Company in 'Indianapolis' City
2025-08-13 15:49:35 - INFO - ❗No matching company found for search_term: Just Add Storage Llc with search_city:Indianapolis
2025-08-13 15:49:36 - INFO - Processing: 'Just As Promised Home Care Llc' Company in 'Indianapolis' City
2025-08-13 15:49:57 - INFO - ❗No matching company found for search_term: Just As Promised Home Care Llc with search_city:Indianapolis
2025-08-13 15:49:58 - INFO - Processing: 'Just Breathe Salt Room & More' Company in 'Angola' City

❌ Error locating company links

2025-08-13 15:50:32 - INFO - Processing: 'Just Cookies' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:51:06 - INFO - Processing: 'Just Desserts Inc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:51:41 - INFO - Processing: 'Just For Granite' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:52:15 - INFO - Processing: 'Just In Trades Llc' Company in 'Noblesville' City
2025-08-13 15:52:35 - INFO - ❗No matching company found for search_term: Just In Trades Llc with search_city:Noblesville
2025-08-13 15:52:36 - INFO - Processing: 'Just Packaging Indianapolis' Company in 'Indianapolis' City
2025-08-13 15:52:57 - INFO - ❗No matching company found for search_term: Just Packaging Indianapolis with search_city:Indianapolis
2025-08-13 15:52:59 - INFO - Processing: 'Just Quilts Llc' Company in 'Albany' City
2025-08-13 15:53:11 - WARNING - No Search results for Just Quilts Llc, continuing to next company
2025-08-13 15:53:12 - INFO - Processing: 'Just Rite Cleaners' Company in 'Carmel' City
2025-08-13 15:53:24 - WARNING - No Search results for Just Rite Cleaners, continuing to next company
2025-08-13 15:53:25 - INFO - Processing: 'Just Security Group Ltd' Company in 'Indianapolis' City
2025-08-13 15:53:46 - INFO - ❗No matching company found for search_term: Just Security Group Ltd with search_city:Indianapolis
2025-08-13 15:53:47 - INFO - Processing: 'Just Shine Cleaners' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 15:54:21 - INFO - Processing: 'Just Skin Solutions Llc' Company in 'Indianapolis' City
2025-08-13 15:54:40 - INFO - ❗No matching company found for search_term: Just Skin Solutions Llc with search_city:Indianapolis
2025-08-13 15:54:41 - INFO - Processing: 'Justice Business Brokers Inc' Company in 'Indianapolis' City
2025-08-13 15:55:00 - INFO - ❗No matching company found for search_term: Justice Business Brokers Inc with search_city:Indianapolis
2025-08-13 15:55:05 - INFO - Processing: 'Justice Of The Peace' Company in 'Indianapolis' City
2025-08-13 15:55:26 - INFO - ❗No matching company found for search_term: Justice Of The Peace with search_city:Indianapolis
2025-08-13 15:55:27 - INFO - Processing: 'Justice Tanya' Company in 'Indianapolis' City
2025-08-13 15:55:39 - WARNING - No Search results for Justice Tanya, continuing to next company
2025-08-13 15:55:40 - INFO - Processing: 'Justin Doresy Plumbing' Company in 'Indianapolis' City
2025-08-13 15:55:52 - WARNING - No Search results for Justin Doresy Plumbing, continuing to next company
2025-08-13 15:55:53 - INFO - Processing: 'Justus Brokerage Co' Company in 'Indianapolis' City
2025-08-13 15:56:11 - INFO - ❗No matching company found for search_term: Justus Brokerage Co with search_city:Indianapolis
2025-08-13 15:56:13 - INFO - Processing: 'Justus Co' Company in 'Indianapolis' City
2025-08-13 15:56:32 - INFO - ❗No matching company found for search_term: Justus Co with search_city:Indianapolis
2025-08-13 15:56:33 - INFO - Processing: 'Jvs Construction Inc' Company in 'Bloomfield' City

❌ Error locating company links

2025-08-13 15:57:08 - INFO - Processing: 'Jvs Transport Llc' Company in 'Carmel' City

❌ Error locating company links

2025-08-13 15:57:42 - INFO - Processing: 'Jw Associates' Company in 'Carmel' City
2025-08-13 15:58:01 - INFO - ❗No matching company found for search_term: Jw Associates with search_city:Carmel
2025-08-13 15:58:02 - INFO - Processing: 'Jwd Enterprises Llc' Company in 'Carthage' City
2025-08-13 15:58:21 - INFO - ❗No matching company found for search_term: Jwd Enterprises Llc with search_city:Carthage
2025-08-13 15:58:22 - INFO - Processing: 'K & A Electrical Solutions' Company in 'Anderson' City
2025-08-13 15:58:42 - INFO - ❗No matching company found for search_term: K & A Electrical Solutions with search_city:Anderson
2025-08-13 15:58:43 - INFO - Processing: 'K & A Trucking Inc' Company in 'Bedford' City
2025-08-13 15:59:04 - INFO - ❗No matching company found for search_term: K & A Trucking Inc with search_city:Bedford
2025-08-13 15:59:08 - INFO - Processing: 'K & B Automotive Repair' Company in 'Anderson' City
2025-08-13 15:59:28 - INFO - ❗No matching company found for search_term: K & B Automotive Repair with search_city:Anderson
2025-08-13 15:59:29 - INFO - Processing: 'K & D Petroleum Inc' Company in 'Brazil' City
2025-08-13 15:59:50 - INFO - ❗No matching company found for search_term: K & D Petroleum Inc with search_city:Brazil
2025-08-13 15:59:51 - INFO - Processing: 'K & E Enterprises' Company in 'Indianapolis' City
2025-08-13 16:00:10 - INFO - ✅ Match found for: K & Jk Enterprises, Inc. | City: Indianapolis | Similarity Score: 83.87096774193549
2025-08-13 16:01:55 - INFO - Processing: 'K & F Industries Inc' Company in 'Indianapolis' City
2025-08-13 16:02:17 - INFO - ❗No matching company found for search_term: K & F Industries Inc with search_city:Indianapolis
2025-08-13 16:02:18 - INFO - Processing: 'K & I Transports Llc' Company in 'Indianapolis' City
2025-08-13 16:02:38 - INFO - ❗No matching company found for search_term: K & I Transports Llc with search_city:Indianapolis
2025-08-13 16:02:39 - INFO - Processing: 'K & J Appliance' Company in 'Indianapolis' City
2025-08-13 16:03:00 - INFO - ❗No matching company found for search_term: K & J Appliance with search_city:Indianapolis
2025-08-13 16:03:01 - INFO - Processing: 'K & J K Enterprises Inc' Company in 'Indianapolis' City
2025-08-13 16:03:21 - INFO - ✅ Match found for: K & Jk Enterprises, Inc. | City: Indianapolis | Similarity Score: 96.96969696969697
2025-08-13 16:05:06 - INFO - Processing: 'K & K Aggregate' Company in 'Indianapolis' City
2025-08-13 16:05:26 - INFO - ❗No matching company found for search_term: K & K Aggregate with search_city:Indianapolis
2025-08-13 16:05:27 - INFO - Processing: 'K & K Cabinets & Supply' Company in 'Brownsburg' City
2025-08-13 16:05:48 - INFO - ❗No matching company found for search_term: K & K Cabinets & Supply with search_city:Brownsburg
2025-08-13 16:05:49 - INFO - Processing: 'K & K Fence' Company in 'Indianapolis' City
2025-08-13 16:06:08 - INFO - ✅ Match found for: K & K Fence Company, Inc. | City: Indianapolis | Similarity Score: 100.0
2025-08-13 16:07:19 - INFO - Processing: 'K & K Locksmith' Company in 'Bedford' City
2025-08-13 16:07:40 - INFO - ❗No matching company found for search_term: K & K Locksmith with search_city:Bedford
2025-08-13 16:07:41 - INFO - Processing: 'K & L Excavating Llc' Company in 'Bedford' City
2025-08-13 16:08:02 - INFO - ❗No matching company found for search_term: K & L Excavating Llc with search_city:Bedford
2025-08-13 16:08:03 - INFO - Processing: 'K & M Fence Llp' Company in 'Indianapolis' City
2025-08-13 16:08:22 - INFO - ✅ Match found for: K & K Fence Company, Inc. | City: Indianapolis | Similarity Score: 88.88888888888889
2025-08-13 16:09:32 - INFO - Processing: 'K & M Remodeling Llc' Company in 'Indianapolis' City
2025-08-13 16:09:53 - INFO - ❗No matching company found for search_term: K & M Remodeling Llc with search_city:Indianapolis
2025-08-13 16:09:54 - INFO - Processing: 'K & R Courier Llc' Company in 'Indianapolis' City
2025-08-13 16:10:14 - INFO - ❗No matching company found for search_term: K & R Courier Llc with search_city:Indianapolis
2025-08-13 16:10:19 - INFO - Processing: 'K & S Recycling Inc' Company in 'Bloomington' City
2025-08-13 16:10:40 - INFO - ❗No matching company found for search_term: K & S Recycling Inc with search_city:Bloomington
2025-08-13 16:10:41 - INFO - Processing: 'K & S Rolloff' Company in 'Bloomington' City
2025-08-13 16:11:02 - INFO - ❗No matching company found for search_term: K & S Rolloff with search_city:Bloomington
2025-08-13 16:11:03 - INFO - Processing: 'K & S Trucking' Company in 'Akron' City
2025-08-13 16:11:24 - INFO - ❗No matching company found for search_term: K & S Trucking with search_city:Akron
2025-08-13 16:11:25 - INFO - Processing: 'K & S Trucking' Company in 'Bloomington' City
2025-08-13 16:11:53 - INFO - ❗No matching company found for search_term: K & S Trucking with search_city:Bloomington
2025-08-13 16:11:54 - INFO - Processing: 'K & S Trucking Inc' Company in 'Akron' City
2025-08-13 16:12:15 - INFO - ❗No matching company found for search_term: K & S Trucking Inc with search_city:Akron
2025-08-13 16:12:16 - INFO - Processing: 'K & T Security' Company in 'Indianapolis' City
2025-08-13 16:12:37 - INFO - ❗No matching company found for search_term: K & T Security with search_city:Indianapolis
2025-08-13 16:12:38 - INFO - Processing: 'K & W Fencing' Company in 'Cannelburg' City
2025-08-13 16:12:59 - INFO - ❗No matching company found for search_term: K & W Fencing with search_city:Cannelburg
2025-08-13 16:13:00 - INFO - Processing: 'K C Brothers Inc' Company in 'Indianapolis' City
2025-08-13 16:13:19 - INFO - ❗No matching company found for search_term: K C Brothers Inc with search_city:Indianapolis
2025-08-13 16:13:20 - INFO - Processing: 'K C Designs' Company in 'Bloomington' City
2025-08-13 16:13:39 - INFO - ❗No matching company found for search_term: K C Designs with search_city:Bloomington
2025-08-13 16:13:40 - INFO - Processing: 'K C Nails' Company in 'Noblesville' City
2025-08-13 16:13:58 - INFO - ❗No matching company found for search_term: K C Nails with search_city:Noblesville
2025-08-13 16:13:59 - INFO - Processing: 'K C Ranch Llc' Company in 'Charlestown' City
2025-08-13 16:14:18 - INFO - ❗No matching company found for search_term: K C Ranch Llc with search_city:Charlestown
2025-08-13 16:14:20 - INFO - Processing: 'K Croom Trucking' Company in 'Highland' City
2025-08-13 16:14:32 - WARNING - No Search results for K Croom Trucking, continuing to next company
2025-08-13 16:14:33 - INFO - Processing: 'K D Carnahan Farms Inc' Company in 'Butler' City
2025-08-13 16:14:53 - INFO - ❗No matching company found for search_term: K D Carnahan Farms Inc with search_city:Butler
2025-08-13 16:14:54 - INFO - Processing: 'K G Construction' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 16:15:29 - INFO - Processing: 'K G Construction' Company in 'Bunker Hill' City

❌ Error locating company links

2025-08-13 16:16:03 - INFO - Processing: 'K J Funke & Assoc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 16:16:37 - INFO - Processing: 'K M Specialty Systems Inc' Company in 'Chandler' City
2025-08-13 16:16:57 - INFO - ✅ Match found for: K M Specialty Systems Inc | City: Chandler | Similarity Score: 100.0
2025-08-13 16:18:42 - INFO - Processing: 'K M Transfer Llc' Company in 'Cedar Lake' City
2025-08-13 16:19:01 - INFO - ❗No matching company found for search_term: K M Transfer Llc with search_city:Cedar Lake
2025-08-13 16:19:02 - INFO - Processing: 'K Nails' Company in 'Indianapolis' City
2025-08-13 16:19:21 - INFO - ❗No matching company found for search_term: K Nails with search_city:Indianapolis
2025-08-13 16:19:21 - INFO - Processing: 'K Nz Heating & Cooling' Company in 'Cedar Lake' City
2025-08-13 16:19:34 - WARNING - No Search results for K Nz Heating & Cooling, continuing to next company
2025-08-13 16:19:35 - INFO - Processing: 'K P Enterprises' Company in 'Indianapolis' City
2025-08-13 16:19:54 - INFO - ❗No matching company found for search_term: K P Enterprises with search_city:Indianapolis
2025-08-13 16:19:55 - INFO - Processing: 'K P Fabrication Llc' Company in 'Avon' City
2025-08-13 16:20:14 - INFO - ❗No matching company found for search_term: K P Fabrication Llc with search_city:Avon
2025-08-13 16:20:15 - INFO - Processing: 'K P Meiring Co' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 16:20:49 - INFO - Processing: 'K P Pharmaceutical Technology' Company in 'Bloomington' City
2025-08-13 16:21:10 - INFO - ✅ Match found for: K.P. Pharmaceutical Technology, Inc. | City: Bloomington | Similarity Score: 98.24561403508771

⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link

2025-08-13 16:23:10 - INFO - Processing: 'K P Pharmaceuticals' Company in 'Bloomington' City
2025-08-13 16:23:21 - WARNING - No Search results for K P Pharmaceuticals, continuing to next company
2025-08-13 16:23:21 - INFO - Processing: 'K P Singh Designs' Company in 'Indianapolis' City
2025-08-13 16:23:33 - WARNING - No Search results for K P Singh Designs, continuing to next company
2025-08-13 16:23:34 - INFO - Processing: 'K P Sullivan Builder Inc' Company in 'Arcadia' City
2025-08-13 16:23:51 - INFO - ✅ Match found for: Kevin P .Sullivan Builders, Inc. | City: Arcadia | Similarity Score: 88.88888888888889
2025-08-13 16:25:09 - INFO - Processing: 'K Paul' Company in 'Indianapolis' City
2025-08-13 16:25:25 - INFO - ❗No matching company found for search_term: K Paul with search_city:Indianapolis
2025-08-13 16:25:27 - INFO - Processing: 'K Specialtys' Company in 'Indianapolis' City
2025-08-13 16:25:44 - INFO - ❗No matching company found for search_term: K Specialtys with search_city:Indianapolis
2025-08-13 16:25:44 - INFO - Processing: 'K T & B Transport Llc' Company in 'Indianapolis' City
2025-08-13 16:26:02 - INFO - ❗No matching company found for search_term: K T & B Transport Llc with search_city:Indianapolis
2025-08-13 16:26:02 - INFO - Processing: 'K T Nails' Company in 'Indianapolis' City
2025-08-13 16:26:13 - WARNING - No Search results for K T Nails, continuing to next company
2025-08-13 16:26:14 - INFO - Processing: 'K T Nails Ii' Company in 'Indianapolis' City
2025-08-13 16:26:25 - WARNING - No Search results for K T Nails Ii, continuing to next company
2025-08-13 16:26:26 - INFO - Processing: 'K W Auto Brokers Llc' Company in 'Bloomfield' City
2025-08-13 16:26:42 - INFO - ❗No matching company found for search_term: K W Auto Brokers Llc with search_city:Bloomfield
2025-08-13 16:26:43 - INFO - Processing: 'K2 Industrial Svc Inc' Company in 'Highland' City
2025-08-13 16:27:01 - INFO - ❗No matching company found for search_term: K2 Industrial Svc Inc with search_city:Highland
2025-08-13 16:27:01 - INFO - Processing: 'K2b Tree Svc Inc' Company in 'Brownsburg' City
2025-08-13 16:27:18 - INFO - ❗No matching company found for search_term: K2b Tree Svc Inc with search_city:Brownsburg
2025-08-13 16:27:18 - INFO - Processing: 'K9 Security Partners' Company in 'Indianapolis' City
2025-08-13 16:27:36 - INFO - ❗No matching company found for search_term: K9 Security Partners with search_city:Indianapolis
2025-08-13 16:27:37 - INFO - Processing: 'K9 Train 4 Results' Company in 'Indianapolis' City
2025-08-13 16:27:53 - INFO - ❗No matching company found for search_term: K9 Train 4 Results with search_city:Indianapolis
2025-08-13 16:27:54 - INFO - Processing: 'Kadampa Meditation Ctr Indnpls' Company in 'Indianapolis' City
2025-08-13 16:28:05 - WARNING - No Search results for Kadampa Meditation Ctr Indnpls, continuing to next company
2025-08-13 16:28:05 - INFO - Processing: 'Kadko Inc' Company in 'Beech Grove' City
2025-08-13 16:28:17 - WARNING - No Search results for Kadko Inc, continuing to next company
2025-08-13 16:28:17 - INFO - Processing: 'Kag Construction Llc' Company in 'Indianapolis' City
2025-08-13 16:28:28 - WARNING - No Search results for Kag Construction Llc, continuing to next company
2025-08-13 16:28:29 - INFO - Processing: 'Kag Tank Svc' Company in 'Indianapolis' City
2025-08-13 16:28:40 - WARNING - No Search results for Kag Tank Svc, continuing to next company
2025-08-13 16:28:41 - INFO - Processing: 'Kairos Enterprise Llc' Company in 'Indianapolis' City
2025-08-13 16:28:58 - INFO - ❗No matching company found for search_term: Kairos Enterprise Llc with search_city:Indianapolis
2025-08-13 16:28:58 - INFO - Processing: 'Kaiser Meat Market' Company in 'Cedar Grove' City
2025-08-13 16:29:09 - WARNING - No Search results for Kaiser Meat Market, continuing to next company
2025-08-13 16:29:10 - INFO - Processing: 'Kaiser Pickles' Company in 'Aurora' City
2025-08-13 16:29:21 - WARNING - No Search results for Kaiser Pickles, continuing to next company
2025-08-13 16:29:22 - INFO - Processing: 'Kalakutah Republic Grill' Company in 'Indianapolis' City
2025-08-13 16:29:33 - WARNING - No Search results for Kalakutah Republic Grill, continuing to next company
2025-08-13 16:29:33 - INFO - Processing: 'Kaldahl Home Improvements' Company in 'Avon' City
2025-08-13 16:29:51 - INFO - ❗No matching company found for search_term: Kaldahl Home Improvements with search_city:Avon
2025-08-13 16:29:52 - INFO - Processing: 'Kalems Enterprises Inc' Company in 'Indianapolis' City
2025-08-13 16:30:08 - INFO - ❗No matching company found for search_term: Kalems Enterprises Inc with search_city:Indianapolis
2025-08-13 16:30:09 - INFO - Processing: 'Kam Hydraulics Inc' Company in 'Indianapolis' City
2025-08-13 16:30:20 - WARNING - No Search results for Kam Hydraulics Inc, continuing to next company
2025-08-13 16:30:21 - INFO - Processing: 'Kamplain Machine Co Inc' Company in 'Indianapolis' City
2025-08-13 16:30:39 - INFO - ❗No matching company found for search_term: Kamplain Machine Co Inc with search_city:Indianapolis
2025-08-13 16:30:39 - INFO - Processing: 'Kamps Pallets Inc' Company in 'Indianapolis' City
2025-08-13 16:30:50 - WARNING - No Search results for Kamps Pallets Inc, continuing to next company
2025-08-13 16:30:51 - INFO - Processing: 'Kanak Exports India Llc' Company in 'Indianapolis' City
2025-08-13 16:31:07 - INFO - ❗No matching company found for search_term: Kanak Exports India Llc with search_city:Indianapolis
2025-08-13 16:31:08 - INFO - Processing: 'Kang Tsou Memorial Fund' Company in 'Bloomington' City
2025-08-13 16:31:19 - WARNING - No Search results for Kang Tsou Memorial Fund, continuing to next company
2025-08-13 16:31:20 - INFO - Processing: 'Kappa Alpha Theta' Company in 'Indianapolis' City
2025-08-13 16:31:36 - INFO - ❗No matching company found for search_term: Kappa Alpha Theta with search_city:Indianapolis
2025-08-13 16:31:37 - INFO - Processing: 'Kappa Alpha Theta Fraternity' Company in 'Indianapolis' City
2025-08-13 16:31:53 - INFO - ✅ Match found for: Kappa Alpha Theta Fraternity | City: Indianapolis | Similarity Score: 100.0
2025-08-13 16:32:21 - INFO - Processing: 'Kappa Alpha Theta Fraternity' Company in 'Bloomington' City
2025-08-13 16:32:44 - INFO - ❗No matching company found for search_term: Kappa Alpha Theta Fraternity with search_city:Bloomington
2025-08-13 16:32:44 - INFO - Processing: 'Kappa Delta Phi' Company in 'Bloomington' City
2025-08-13 16:32:56 - WARNING - No Search results for Kappa Delta Phi, continuing to next company
2025-08-13 16:32:56 - INFO - Processing: 'Kappa Delta Pi' Company in 'Indianapolis' City
2025-08-13 16:33:13 - INFO - ✅ Match found for: Kappa Delta Pi | City: Indianapolis | Similarity Score: 100.0
2025-08-13 16:34:05 - INFO - Processing: 'Kappa Delta Sigma Upsilon Assn' Company in 'Bloomington' City
2025-08-13 16:34:16 - WARNING - No Search results for Kappa Delta Sigma Upsilon Assn, continuing to next company
2025-08-13 16:34:17 - INFO - Processing: 'Kappa Delta Sorority' Company in 'Bloomington' City
2025-08-13 16:34:28 - WARNING - No Search results for Kappa Delta Sorority, continuing to next company
2025-08-13 16:34:29 - INFO - Processing: 'Kappa Kappa Gamma Chapter Hse' Company in 'Bloomington' City
2025-08-13 16:34:40 - WARNING - No Search results for Kappa Kappa Gamma Chapter Hse, continuing to next company
2025-08-13 16:34:40 - INFO - Processing: 'Kappa Kappa Kappa Inc' Company in 'Alexandria' City
2025-08-13 16:34:57 - INFO - ❗No matching company found for search_term: Kappa Kappa Kappa Inc with search_city:Alexandria
2025-08-13 16:34:58 - INFO - Processing: 'Kappa Kappa Kappa Inc' Company in 'Avon' City
2025-08-13 16:35:21 - INFO - ❗No matching company found for search_term: Kappa Kappa Kappa Inc with search_city:Avon
2025-08-13 16:35:21 - INFO - Processing: 'Kappa Kappa Kappa Inc' Company in 'Camden' City
2025-08-13 16:35:45 - INFO - ❗No matching company found for search_term: Kappa Kappa Kappa Inc with search_city:Camden
2025-08-13 16:35:45 - INFO - Processing: 'Kappa Psi Pharmaceutical' Company in 'Indianapolis' City
2025-08-13 16:35:57 - WARNING - No Search results for Kappa Psi Pharmaceutical, continuing to next company
2025-08-13 16:35:57 - INFO - Processing: 'Kapps Green Lawn' Company in 'Indianapolis' City
2025-08-13 16:36:14 - INFO - ❗No matching company found for search_term: Kapps Green Lawn with search_city:Indianapolis
2025-08-13 16:36:15 - INFO - Processing: 'Karen Hall & Co' Company in 'Indianapolis' City
2025-08-13 16:36:26 - WARNING - No Search results for Karen Hall & Co, continuing to next company
2025-08-13 16:36:27 - INFO - Processing: 'Karen L Bean Irrevocable Pvt' Company in 'Carmel' City

❌ Error locating company links

2025-08-13 16:36:59 - INFO - Processing: 'Kar-kwik Muffler Shops' Company in 'Bedford' City

❌ Error locating company links

2025-08-13 16:37:32 - INFO - Processing: 'Karl Hinkle Music Ministries' Company in 'Carmel' City
2025-08-13 16:37:49 - INFO - ❗No matching company found for search_term: Karl Hinkle Music Ministries with search_city:Carmel
2025-08-13 16:37:49 - INFO - Processing: 'Karma Records' Company in 'Indianapolis' City
2025-08-13 16:38:00 - WARNING - No Search results for Karma Records, continuing to next company
2025-08-13 16:38:01 - INFO - Processing: 'Karns Inc' Company in 'Indianapolis' City
2025-08-13 16:38:18 - INFO - ✅ Match found for: Karns, Inc. | City: Indianapolis | Similarity Score: 100.0

Login failed
⚠️ Error processing link

2025-08-13 16:40:05 - INFO - Processing: 'Karter Paige Essentials Hair' Company in 'Indianapolis' City
2025-08-13 16:40:16 - WARNING - No Search results for Karter Paige Essentials Hair, continuing to next company
2025-08-13 16:40:16 - INFO - Processing: 'Kaser Appraisal & Real Est Svc' Company in 'Carmel' City
2025-08-13 16:40:28 - WARNING - No Search results for Kaser Appraisal & Real Est Svc, continuing to next company
2025-08-13 16:40:31 - INFO - Processing: 'Kasey Program' Company in 'Indianapolis' City
2025-08-13 16:40:48 - INFO - ❗No matching company found for search_term: Kasey Program with search_city:Indianapolis
2025-08-13 16:40:48 - INFO - Processing: 'Kash Cleaners' Company in 'Indianapolis' City
2025-08-13 16:40:59 - WARNING - No Search results for Kash Cleaners, continuing to next company
2025-08-13 16:41:00 - INFO - Processing: 'Kashan Oriental Rug' Company in 'Bloomington' City
2025-08-13 16:41:11 - WARNING - No Search results for Kashan Oriental Rug, continuing to next company
2025-08-13 16:41:12 - INFO - Processing: 'Kasnak Restorations' Company in 'Brownsburg' City
2025-08-13 16:41:23 - WARNING - No Search results for Kasnak Restorations, continuing to next company
2025-08-13 16:41:24 - INFO - Processing: 'Kastens Dog Training Inc' Company in 'Bristol' City
2025-08-13 16:41:40 - INFO - ❗No matching company found for search_term: Kastens Dog Training Inc with search_city:Bristol
2025-08-13 16:41:41 - INFO - Processing: 'Kastoria Associates Llc' Company in 'Indianapolis' City
2025-08-13 16:41:52 - WARNING - No Search results for Kastoria Associates Llc, continuing to next company
2025-08-13 16:41:53 - INFO - Processing: 'Katalyst Corp' Company in 'Beech Grove' City
2025-08-13 16:42:09 - INFO - ✅ Match found for: Katalyst Llc | City: Beech Grove | Similarity Score: 100.0
2025-08-13 16:43:17 - INFO - Processing: 'Kathys Hair Fashions' Company in 'Indianapolis' City
2025-08-13 16:43:28 - WARNING - No Search results for Kathys Hair Fashions, continuing to next company
2025-08-13 16:43:29 - INFO - Processing: 'Kathys Style-fashion Beauty' Company in 'Brownstown' City
2025-08-13 16:43:40 - WARNING - No Search results for Kathys Style-fashion Beauty, continuing to next company
2025-08-13 16:43:41 - INFO - Processing: 'Kats Tree & Landscape' Company in 'Indianapolis' City
2025-08-13 16:43:52 - WARNING - No Search results for Kats Tree & Landscape, continuing to next company
2025-08-13 16:43:53 - INFO - Processing: 'Katsumis Teaching Kitchen Llc' Company in 'Indianapolis' City
2025-08-13 16:44:04 - WARNING - No Search results for Katsumis Teaching Kitchen Llc, continuing to next company
2025-08-13 16:44:04 - INFO - Processing: 'Kaufman Global' Company in 'Carmel' City
2025-08-13 16:44:21 - INFO - ❗No matching company found for search_term: Kaufman Global with search_city:Carmel
2025-08-13 16:44:22 - INFO - Processing: 'Kautex' Company in 'Avilla' City
2025-08-13 16:44:33 - WARNING - No Search results for Kautex, continuing to next company
2025-08-13 16:44:37 - INFO - Processing: 'Kawneer Co Inc' Company in 'Batesville' City
2025-08-13 16:44:54 - INFO - ❗No matching company found for search_term: Kawneer Co Inc with search_city:Batesville
2025-08-13 16:44:54 - INFO - Processing: 'Kayla Root Salon Llc' Company in 'Indianapolis' City
2025-08-13 16:45:06 - WARNING - No Search results for Kayla Root Salon Llc, continuing to next company
2025-08-13 16:45:06 - INFO - Processing: 'Kb Beauty Space' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 16:45:39 - INFO - Processing: 'Kb Cleaning' Company in 'Cedar Lake' City
2025-08-13 16:45:51 - WARNING - No Search results for Kb Cleaning, continuing to next company
2025-08-13 16:45:51 - INFO - Processing: 'Kb Kuts Salon' Company in 'Indianapolis' City
2025-08-13 16:46:02 - WARNING - No Search results for Kb Kuts Salon, continuing to next company
2025-08-13 16:46:03 - INFO - Processing: 'Kb Masonry' Company in 'Indianapolis' City
2025-08-13 16:46:14 - WARNING - No Search results for Kb Masonry, continuing to next company
2025-08-13 16:46:15 - INFO - Processing: 'Kb Mechanical Inc' Company in 'Walkerton' City
2025-08-13 16:46:31 - INFO - ❗No matching company found for search_term: Kb Mechanical Inc with search_city:Walkerton
2025-08-13 16:46:32 - INFO - Processing: 'Kba Industries Llc' Company in 'Indianapolis' City
2025-08-13 16:46:43 - WARNING - No Search results for Kba Industries Llc, continuing to next company
2025-08-13 16:46:43 - INFO - Processing: 'Kbc Machines Inc' Company in 'Indianapolis' City
2025-08-13 16:47:01 - INFO - ❗No matching company found for search_term: Kbc Machines Inc with search_city:Indianapolis
2025-08-13 16:47:02 - INFO - Processing: 'Kbf Buck Creek Llc' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 16:47:35 - INFO - Processing: 'Kbk Inc' Company in 'Indianapolis' City
2025-08-13 16:47:46 - WARNING - No Search results for Kbk Inc, continuing to next company
2025-08-13 16:47:47 - INFO - Processing: 'KBL' Company in 'Berne' City
2025-08-13 16:48:03 - INFO - ❗No matching company found for search_term: KBL with search_city:Berne
2025-08-13 16:48:04 - INFO - Processing: 'Kc Cakes Unlimited' Company in 'Noblesville' City
2025-08-13 16:48:15 - WARNING - No Search results for Kc Cakes Unlimited, continuing to next company
2025-08-13 16:48:16 - INFO - Processing: 'Kcg Development' Company in 'Indianapolis' City
2025-08-13 16:48:34 - INFO - ❗No matching company found for search_term: Kcg Development with search_city:Indianapolis
2025-08-13 16:48:34 - INFO - Processing: 'K-copack' Company in 'Ashley' City
2025-08-13 16:48:52 - INFO - ❗No matching company found for search_term: K-copack with search_city:Ashley
2025-08-13 16:48:53 - INFO - Processing: 'Kdc Body Shop Inc' Company in 'Indianapolis' City
2025-08-13 16:49:10 - INFO - ❗No matching company found for search_term: Kdc Body Shop Inc with search_city:Indianapolis
2025-08-13 16:49:10 - INFO - Processing: 'Kdc Truck & Trailer Repair Inc' Company in 'Indianapolis' City
2025-08-13 16:49:22 - WARNING - No Search results for Kdc Truck & Trailer Repair Inc, continuing to next company
2025-08-13 16:49:23 - INFO - Processing: 'Kdm Express Llc' Company in 'Carmel' City
2025-08-13 16:49:39 - INFO - ✅ Match found for: Kdm Express, Inc. | City: Carmel | Similarity Score: 100.0
2025-08-13 16:51:11 - INFO - Processing: 'Keco Engineered Coatings' Company in 'Indianapolis' City
2025-08-13 16:51:27 - INFO - ✅ Match found for: KECO Engineered Coatings, Inc. | City: Indianapolis | Similarity Score: 100.0

Login failed
⚠️ Error processing link
⚠️ Error processing link

2025-08-13 16:52:25 - INFO - Processing: 'Keen Co Inc' Company in 'Indianapolis' City
2025-08-13 16:52:41 - INFO - ✅ Match found for: Keen Company Inc | City: Indianapolis | Similarity Score: 100.0
2025-08-13 16:54:00 - INFO - Processing: 'Keen Concrete Contracting' Company in 'Brazil' City
2025-08-13 16:54:11 - WARNING - No Search results for Keen Concrete Contracting, continuing to next company
2025-08-13 16:54:12 - INFO - Processing: 'Keeneland Park Homeowners Assn' Company in 'Carmel' City
2025-08-13 16:54:24 - WARNING - No Search results for Keeneland Park Homeowners Assn, continuing to next company
2025-08-13 16:54:24 - INFO - Processing: 'Keep Indianapolis Beautiful' Company in 'Indianapolis' City
2025-08-13 16:54:41 - INFO - ✅ Match found for: Keep Indianapolis Beautiful, Inc. | City: Indianapolis | Similarity Score: 100.0

Login failed
⚠️ Error processing link

2025-08-13 16:55:38 - INFO - Processing: 'Keep It Clean Car Wash East' Company in 'Batesville' City
2025-08-13 16:55:55 - INFO - ❗No matching company found for search_term: Keep It Clean Car Wash East with search_city:Batesville
2025-08-13 16:55:56 - INFO - Processing: 'Keep It Kleen' Company in 'Batesville' City

❌ Error locating company links

2025-08-13 16:56:28 - INFO - Processing: 'Keep It Moving Hair Design' Company in 'Indianapolis' City
2025-08-13 16:56:45 - INFO - ❗No matching company found for search_term: Keep It Moving Hair Design with search_city:Indianapolis
2025-08-13 16:56:46 - INFO - Processing: 'Keep It U-lock Storage' Company in 'Cedar Lake' City
2025-08-13 16:57:04 - INFO - ❗No matching company found for search_term: Keep It U-lock Storage with search_city:Cedar Lake
2025-08-13 16:57:04 - INFO - Processing: 'Keep Off The Grass Lawn Svc' Company in 'Indianapolis' City
2025-08-13 16:57:16 - WARNING - No Search results for Keep Off The Grass Lawn Svc, continuing to next company
2025-08-13 16:57:17 - INFO - Processing: 'Keep Your Head Up Barber Shop' Company in 'Indianapolis' City
2025-08-13 16:57:30 - WARNING - No Search results for Keep Your Head Up Barber Shop, continuing to next company
2025-08-13 16:57:30 - INFO - Processing: 'Keeping It Real Ministries' Company in 'Indianapolis' City
2025-08-13 16:57:47 - INFO - ❗No matching company found for search_term: Keeping It Real Ministries with search_city:Indianapolis
2025-08-13 16:57:47 - INFO - Processing: 'Keesling Custom Pools & Patios' Company in 'Indianapolis' City
2025-08-13 16:57:59 - WARNING - No Search results for Keesling Custom Pools & Patios, continuing to next company
2025-08-13 16:58:00 - INFO - Processing: 'Keihin' Company in 'Anderson' City
2025-08-13 16:58:18 - INFO - ❗No matching company found for search_term: Keihin with search_city:Anderson
2025-08-13 16:58:19 - INFO - Processing: 'Keita Ilouyassou' Company in 'Indianapolis' City
2025-08-13 16:58:30 - WARNING - No Search results for Keita Ilouyassou, continuing to next company
2025-08-13 16:58:31 - INFO - Processing: 'Keith Gunter Excavating' Company in 'Batesville' City
2025-08-13 16:58:42 - WARNING - No Search results for Keith Gunter Excavating, continuing to next company
2025-08-13 16:58:42 - INFO - Processing: 'Keith Harris Construction Llc' Company in 'Indianapolis' City
2025-08-13 16:58:54 - WARNING - No Search results for Keith Harris Construction Llc, continuing to next company
2025-08-13 16:58:55 - INFO - Processing: 'Keith Shade Co Inc' Company in 'Indianapolis' City
2025-08-13 16:59:06 - WARNING - No Search results for Keith Shade Co Inc, continuing to next company
2025-08-13 16:59:07 - INFO - Processing: 'Keiths Lawncare & Landscape' Company in 'Angola' City
2025-08-13 16:59:19 - WARNING - No Search results for Keiths Lawncare & Landscape, continuing to next company
2025-08-13 16:59:20 - INFO - Processing: 'Keller Air Conditioning Svc' Company in 'Berne' City
2025-08-13 16:59:31 - WARNING - No Search results for Keller Air Conditioning Svc, continuing to next company
2025-08-13 16:59:32 - INFO - Processing: 'Keller Heating & Air Cond Inc' Company in 'Bloomington' City
2025-08-13 16:59:44 - WARNING - No Search results for Keller Heating & Air Cond Inc, continuing to next company
2025-08-13 16:59:45 - INFO - Processing: 'Keller Rivest' Company in 'Indianapolis' City
2025-08-13 17:00:02 - INFO - ✅ Match found for: Keller Rivest, LLC | City: Indianapolis | Similarity Score: 100.0
2025-08-13 17:01:26 - INFO - Processing: 'Kellers Roofing & Restoration' Company in 'Carmel' City

❌ Error locating company links

2025-08-13 17:01:58 - INFO - Processing: 'Kelley Bros Hardware Corp' Company in 'Indianapolis' City
2025-08-13 17:02:14 - INFO - ❗No matching company found for search_term: Kelley Bros Hardware Corp with search_city:Indianapolis
2025-08-13 17:02:15 - INFO - Processing: 'Kelley Bros Llc' Company in 'Indianapolis' City
2025-08-13 17:02:26 - WARNING - No Search results for Kelley Bros Llc, continuing to next company
2025-08-13 17:02:26 - INFO - Processing: 'Kelley Electric' Company in 'Anderson' City
2025-08-13 17:02:43 - INFO - ❗No matching company found for search_term: Kelley Electric with search_city:Anderson
2025-08-13 17:02:44 - INFO - Processing: 'Kelley Engineering' Company in 'Brookston' City
2025-08-13 17:03:01 - INFO - ❗No matching company found for search_term: Kelley Engineering with search_city:Brookston
2025-08-13 17:03:01 - INFO - Processing: 'Kelley Flooring' Company in 'Brownsburg' City
2025-08-13 17:03:13 - WARNING - No Search results for Kelley Flooring, continuing to next company
2025-08-13 17:03:13 - INFO - Processing: 'Kelleys Termite-pest Control' Company in 'Bloomington' City
2025-08-13 17:03:30 - INFO - ❗No matching company found for search_term: Kelleys Termite-pest Control with search_city:Bloomington
2025-08-13 17:03:31 - INFO - Processing: 'Kellies Hair Designers' Company in 'Indianapolis' City
2025-08-13 17:03:42 - WARNING - No Search results for Kellies Hair Designers, continuing to next company
2025-08-13 17:03:42 - INFO - Processing: 'Kelly Box & Packaging Inc' Company in 'Indianapolis' City
2025-08-13 17:03:59 - INFO - ❗No matching company found for search_term: Kelly Box & Packaging Inc with search_city:Indianapolis
2025-08-13 17:03:59 - INFO - Processing: 'Kelly Landscaping' Company in 'Indianapolis' City

❌ Error locating company links

2025-08-13 17:04:31 - INFO - Processing: 'Kelly Nail Professional' Company in 'Avon' City
2025-08-13 17:04:43 - WARNING - No Search results for Kelly Nail Professional, continuing to next company
2025-08-13 17:04:43 - INFO - Processing: 'Kelly Services' Company in 'Indianapolis' City
2025-08-13 17:05:01 - INFO - ❗No matching company found for search_term: Kelly Services with search_city:Indianapolis
2025-08-13 17:05:02 - INFO - Processing: 'Kelly Services' Company in 'Bloomington' City
2025-08-13 17:05:26 - INFO - ❗No matching company found for search_term: Kelly Services with search_city:Bloomington
2025-08-13 17:05:26 - INFO - Processing: 'Kelly Shea Travels Llc' Company in 'Carmel' City
2025-08-13 17:05:43 - INFO - ❗No matching company found for search_term: Kelly Shea Travels Llc with search_city:Carmel
2025-08-13 17:05:44 - INFO - Processing: 'Kelly Trucking Inc' Company in 'Argos' City
2025-08-13 17:05:55 - WARNING - No Search results for Kelly Trucking Inc, continuing to next company
2025-08-13 17:05:55 - INFO - Processing: 'Kellys Cleaning Svc Llc' Company in 'Charlestown' City
2025-08-13 17:06:11 - INFO - ❗No matching company found for search_term: Kellys Cleaning Svc Llc with search_city:Charlestown
2025-08-13 17:06:12 - INFO - Processing: 'Kellys Collision Ctr Inc' Company in 'Bluffton' City
2025-08-13 17:06:23 - WARNING - No Search results for Kellys Collision Ctr Inc, continuing to next company
2025-08-13 17:06:24 - INFO - Processing: 'Keltner Property Group Llc' Company in 'Carmel' City
2025-08-13 17:06:40 - INFO - ✅ Match found for: Lauth Property Group, LLC | City: Carmel | Similarity Score: 80.95238095238095

Login failed
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link
⚠️ Error processing link

2025-08-13 17:07:31 - INFO - Processing: 'Kelvin Handyman Svc' Company in 'Indianapolis' City
2025-08-13 17:07:42 - WARNING - No Search results for Kelvin Handyman Svc, continuing to next company
2025-08-13 17:07:42 - INFO - Processing: 'Kelvion Inc' Company in 'Indianapolis' City
2025-08-13 17:07:59 - INFO - ❗No matching company found for search_term: Kelvion Inc with search_city:Indianapolis
2025-08-13 17:07:59 - INFO - Processing: 'Kemna Restoration' Company in 'Indianapolis' City
2025-08-13 17:08:15 - INFO - ❗No matching company found for search_term: Kemna Restoration with search_city:Indianapolis
2025-08-13 17:08:16 - INFO - Processing: 'Kemna Restoration & Constr' Company in 'Indianapolis' City
2025-08-13 17:08:32 - INFO - ✅ Match found for: Kemna Restoration & Construction, Inc. | City: Indianapolis | Similarity Score: 88.88888888888889
2025-08-13 17:09:15 - INFO - Processing: 'Kemp Inc' Company in 'Cannelburg' City
2025-08-13 17:09:32 - INFO - ❗No matching company found for search_term: Kemp Inc with search_city:Cannelburg
2025-08-13 17:09:32 - INFO - Processing: 'Kemp Transport Systems Llc' Company in 'Indianapolis' City
2025-08-13 17:09:50 - INFO - ❗No matching company found for search_term: Kemp Transport Systems Llc with search_city:Indianapolis
2025-08-13 17:09:50 - INFO - Processing: 'Kemper Construction Co' Company in 'Aurora' City

❌ Error locating company links

2025-08-13 17:10:23 - INFO - Processing: 'Ken Cut Lawn Svc Inc' Company in 'Indianapolis' City
2025-08-13 17:10:40 - INFO - ❗No matching company found for search_term: Ken Cut Lawn Svc Inc with search_city:Indianapolis
2025-08-13 17:10:44 - INFO - Processing: 'Ken Gates Ministries Inc' Company in 'Indianapolis' City
2025-08-13 17:10:55 - WARNING - No Search results for Ken Gates Ministries Inc, continuing to next company
2025-08-13 17:10:56 - INFO - Processing: 'Ken Kleen Inc' Company in 'Indianapolis' City
2025-08-13 17:11:07 - WARNING - No Search results for Ken Kleen Inc, continuing to next company
2025-08-13 17:11:07 - INFO - Processing: 'Ken Maddox Htg & Air Cond Inc' Company in 'Indianapolis' City
2025-08-13 17:11:19 - WARNING - No Search results for Ken Maddox Htg & Air Cond Inc, continuing to next company
2025-08-13 17:11:19 - INFO - Processing: 'Ken Skinner Construction' Company in 'Bloomfield' City
2025-08-13 17:11:30 - WARNING - No Search results for Ken Skinner Construction, continuing to next company
2025-08-13 17:11:31 - INFO - Processing: 'Kendall Bail Bonding' Company in 'Indianapolis' City
2025-08-13 17:11:42 - WARNING - No Search results for Kendall Bail Bonding, continuing to next company
2025-08-13 17:11:42 - INFO - Processing: 'Kendall Electric Inc' Company in 'Angola' City
2025-08-13 17:11:59 - INFO - ❗No matching company found for search_term: Kendall Electric Inc with search_city:Angola
2025-08-13 17:12:00 - INFO - Processing: 'Kendall Electric Inc' Company in 'Auburn' City
2025-08-13 17:12:23 - INFO - ❗No matching company found for search_term: Kendall Electric Inc with search_city:Auburn
2025-08-13 17:12:23 - INFO - Processing: 'Kendall Inventory Svc Llc' Company in 'Indianapolis' City
2025-08-13 17:12:35 - WARNING - No Search results for Kendall Inventory Svc Llc, continuing to next company
2025-08-13 17:12:35 - INFO - Processing: 'Kendall Pest Control' Company in 'Indianapolis' City
2025-08-13 17:12:52 - INFO - ❗No matching company found for search_term: Kendall Pest Control with search_city:Indianapolis
2025-08-13 17:12:53 - INFO - Processing: 'Kendall Pool Svc' Company in 'Indianapolis' City
2025-08-13 17:13:04 - WARNING - No Search results for Kendall Pool Svc, continuing to next company
2025-08-13 17:13:05 - INFO - Processing: 'Kendall Property Group' Company in 'Indianapolis' City
2025-08-13 17:13:22 - INFO - ✅ Match found for: Kendall Property Group, Inc. | City: Indianapolis | Similarity Score: 100.0

KeyboardInterrupt:

In [13]:
# Create a DataFrame
import pandas as pd
df2 = pd.DataFrame(all_company_data)

# Step 1: Explode the 'Key People' column to separate rows
company_data_exploded = df2.explode('Key People')

# Step 2: Extract 'Name' and 'Title' from each dictionary
company_data_exploded['Executive Name'] = company_data_exploded['Key People'].apply(lambda x: x['Name'] if isinstance(x, dict) and 'Name' in x else None)
company_data_exploded['Executive Title'] = company_data_exploded['Key People'].apply(lambda x: x['Title'] if isinstance(x, dict) and 'Title' in x else None)
company_data_exploded['LinkedIN Profile'] = company_data_exploded['Key People'].apply(lambda x: x['LinkedIN Profile'] if isinstance(x, dict) and 'LinkedIN Profile' in x else None)

# Step 3: Drop the original 'Key People' column
company_data_exploded = company_data_exploded.drop(columns=['Key People'])
# Step 4: Map LinkedIn profiles to each executive
# company_data_exploded['LinkedIN Profiles'] = company_data_exploded['Executive Name'].map(linkedin_profiles)
# new_col_order = ["Employer Name", "City", "NAICS Code", "Industry", "Description", "Website URL", "Headquarters",
#                  "Current_Headcount", "Percent_Change_in_HC", "Change_in_HC", "CEO Name","CEO Profile Link", "LinkedIN URL", 
#                  "Executive Name", "Executive Title", "LinkedIN Profiles"]
# company_data_exploded = company_data_exploded[new_col_order]

In [14]:
company_data_exploded

,Employer Name,City,NAICS Code,Industry,Description,Website URL,Headquarters,Current_Headcount,Percent_Change_in_HC,Change_in_HC,CEO Name,CEO Profile Link,LinkedIN URL,Executive Name,Executive Title,LinkedIN Profile
0,Jehovahs Witnesses,Charlestown,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None
1,Jehovahs Witnesses,Indianapolis,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None
2,Jehovahs Witnesses,Aurora,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None
3,Jehovahs Witnesses,Bloomington,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None
4,Jehovahs Witnesses,Bluffton,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548,Kendall Electric Inc,Angola,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None
549,Kendall Electric Inc,Auburn,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None
550,Kendall Inventory Svc Llc,Indianapolis,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None
551,Kendall Pest Control,Indianapolis,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None
552,Kendall Pool Svc,Indianapolis,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None

In [15]:
company_data_exploded.to_excel(r"C:\Users\IlaBarshilia\OneDrive - OIA Global\VS_Code\CapIQ_Web_Scraping_Output_110042-115149_Companies.xlsx", index=False)

In [15]:
# Create a DataFrame
df2 = pd.DataFrame(all_company_data)

# Step 1: Explode the 'Key People' column to separate rows
company_data_exploded = df2.explode('Key People')

# Step 2: Extract 'Name' and 'Title' from each dictionary
company_data_exploded['Executive Name'] = company_data_exploded['Key People'].apply(lambda x: x['Name'] if isinstance(x, dict) and 'Name' in x else None)
company_data_exploded['Executive Title'] = company_data_exploded['Key People'].apply(lambda x: x['Title'] if isinstance(x, dict) and 'Title' in x else None)

# Step 3: Drop the original 'Key People' column
company_data_exploded = company_data_exploded.drop(columns=['Key People'])
company_data_exploded
# Step 4: Map LinkedIn profiles to each executive
# company_data_exploded['LinkedIN Profiles'] = company_data_exploded['Executive Name'].map(linkedin_profiles)
# new_col_order = ["Employer Name", "City", "NAICS Code", "Industry", "Description", "Website URL", "Headquarters",
#                  "Current_Headcount", "Percent_Change_in_HC", "Change_in_HC", "CEO Name","CEO Profile Link", "LinkedIN URL", 
#                  "Executive Name", "Executive Title", "LinkedIN Profiles"]
# company_data_exploded = company_data_exploded[new_col_order]

,Employer Name,City,NAICS Code,Industry,Description,Website URL,Headquarters,Current_Headcount,Percent_Change_in_HC,Change_in_HC,CEO Name,CEO Profile Link,LinkedIN URL,LinkedIN Profiles,Executive Name,Executive Title
0,Polygon Co,Walkerton,326121 - Unlaminated Plastics Profile Shape Ma...,Commodity Chemicals,"Polygon Company, Inc., an engineered materials...",http://www.polygoncomposites.com/,"103 Industrial Park Drive, PO Box 176, Walkert...",74,5,-1,Bree Katulak,https://www.capitaliq.spglobal.com/web/client#...,https://www.linkedin.com/company/polygon-compo...,{'Bree Katulak': 'https://www.linkedin.com/in/...,Bree Katulak,President & CEO
0,Polygon Co,Walkerton,326121 - Unlaminated Plastics Profile Shape Ma...,Commodity Chemicals,"Polygon Company, Inc., an engineered materials...",http://www.polygoncomposites.com/,"103 Industrial Park Drive, PO Box 176, Walkert...",74,5,-1,Bree Katulak,https://www.capitaliq.spglobal.com/web/client#...,https://www.linkedin.com/company/polygon-compo...,{'Bree Katulak': 'https://www.linkedin.com/in/...,Jim Hoffman,Vice President of Finance & IT
0,Polygon Co,Walkerton,326121 - Unlaminated Plastics Profile Shape Ma...,Commodity Chemicals,"Polygon Company, Inc., an engineered materials...",http://www.polygoncomposites.com/,"103 Industrial Park Drive, PO Box 176, Walkert...",74,5,-1,Bree Katulak,https://www.capitaliq.spglobal.com/web/client#...,https://www.linkedin.com/company/polygon-compo...,{'Bree Katulak': 'https://www.linkedin.com/in/...,Ben Fouch,Vice President of Strategy & Operations
0,Polygon Co,Walkerton,326121 - Unlaminated Plastics Profile Shape Ma...,Commodity Chemicals,"Polygon Company, Inc., an engineered materials...",http://www.polygoncomposites.com/,"103 Industrial Park Drive, PO Box 176, Walkert...",74,5,-1,Bree Katulak,https://www.capitaliq.spglobal.com/web/client#...,https://www.linkedin.com/company/polygon-compo...,{'Bree Katulak': 'https://www.linkedin.com/in/...,Doug Drummond,Vice President of Sales & Marketing

In [17]:
df2["Key People"]

0    [{'Name': 'Bree Katulak', 'Title': 'President ...
Name: Key People, dtype: object

In [15]:
df2 = pd.DataFrame(all_company_data)
df2.to_excel(r"C:\Users\IlaBarshilia\OneDrive - OIA Global\VS_Code\Capital_IQ_WebScraping_100Companies_Consolidated.xlsx", index=False)

In [14]:
# Step 1: Explode the 'Key People' column to separate rows
company_data_exploded = df2.explode('Key People')

# Step 2: Extract 'Name' and 'Title' from each dictionary
company_data_exploded['Executive Name'] = company_data_exploded['Key People'].apply(lambda x: x['Name'] if isinstance(x, dict) and 'Name' in x else None)
company_data_exploded['Executive Title'] = company_data_exploded['Key People'].apply(lambda x: x['Title'] if isinstance(x, dict) and 'Title' in x else None)

# Step 3: Drop the original 'Key People' column
company_data_exploded = company_data_exploded.drop(columns=['Key People'])
# Step 4: Map LinkedIn profiles to each executive
company_data_exploded['LinkedIN Profiles'] = company_data_exploded['Executive Name'].map(linkedin_profiles)
new_col_order = ["Employer Name", "City", "NAICS Code", "Industry", "Description", "Website URL", "Headquarters",
                 "Current_Headcount", "Percent_Change_in_HC", "Change_in_HC", "CEO Name","CEO Profile Link", "LinkedIN URL", 
                 "Executive Name", "Executive Title", "LinkedIN Profiles"]
company_data_exploded = company_data_exploded[new_col_order]
company_data_exploded.to_excel(r"C:\Users\IlaBarshilia\OneDrive - OIA Global\VS_Code\Capital_IQ_WebScraping_100Companies_Exploded.xlsx", index=False)